import { useState } from 'react';
import { Alert,Pressable,ScrollView,StyleSheet,Text,TextInput,View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { colors,radii } from '../../lib/theme';
import { supabase } from '../../lib/supabase';
import { usePreferences } from '../../lib/preferences-context';
import { localize } from '../../lib/i18n';

export default function Passport(){
 const prefs=usePreferences();const L=(en:string,fr:string,es:string)=>localize(prefs.language,en,fr,es);
 const[nationality,setNationality]=useState(''),[passportRef,setPassportRef]=useState(''),[country,setCountry]=useState(''),[expires,setExpires]=useState(''),[saving,setSaving]=useState(false),[error,setError]=useState('');
 async function submit(){if(!supabase)return;setError('');if(!nationality.trim()||!passportRef.trim()||!country.trim())return setError(L('Nationality, passport reference and issuing country are required.','Nationalité, référence du passeport et pays émetteur requis.','Nacionalidad, referencia del pasaporte y país emisor obligatorios.'));if(expires.trim()&&!/^\d{4}-\d{2}-\d{2}$/.test(expires.trim()))return setError('YYYY-MM-DD');setSaving(true);try{const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error(L('Session expired','Session expirée','Sesión caducada'));const p=await supabase.from('professionals').update({nationality:nationality.trim()}).eq('id',user.id);if(p.error)throw p.error;const existing=await supabase.from('professional_documents').select('id').eq('professional_id',user.id).eq('document_type','passport').eq('status','pending').limit(1);if(existing.error)throw existing.error;if(existing.data?.[0]){const u=await supabase.from('professional_documents').update({title:'Passport identity reference',reference:passportRef.trim(),expires_at:expires.trim()||null}).eq('id',existing.data[0].id);if(u.error)throw u.error}else{const i=await supabase.from('professional_documents').insert({professional_id:user.id,document_type:'passport',title:`Passport · ${country.trim()}`,reference:passportRef.trim(),expires_at:expires.trim()||null,status:'pending'});if(i.error)throw i.error}router.replace('/professional/verification')}catch(e:any){setError(e?.message||'MediCrew')}finally{setSaving(false)}}
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.container} keyboardShouldPersistTaps="handled"><Text style={s.eyebrow}>{L('IDENTITY VERIFICATION · 1/2','VÉRIFICATION IDENTITÉ · 1/2','VERIFICACIÓN DE IDENTIDAD · 1/2')}</Text><Text style={s.title}>{L('Identity reference.','Référence d’identité.','Referencia de identidad.')}</Text><Text style={s.sub}>{L('To keep data use low, MediCrew does not require a passport file here. Enter the official reference exactly as shown on your passport. It stays private and is used only by the MediCrew verification team.','Pour limiter les données stockées, MediCrew ne demande pas le fichier du passeport ici. Saisissez la référence officielle exactement comme sur votre passeport. Elle reste privée et n’est utilisée que par l’équipe de vérification MediCrew.','Para limitar los datos almacenados, MediCrew no pide el archivo del pasaporte aquí. Introduce la referencia oficial exactamente como aparece en tu pasaporte. Permanece privada y solo la usa el equipo de verificación.')}</Text>{error?<View style={s.error}><Text style={s.errorText}>{error}</Text></View>:null}<View style={s.card}><Field label={L('Nationality','Nationalité','Nacionalidad')} value={nationality} set={setNationality}/><Field label={L('Passport issuing country','Pays émetteur du passeport','País emisor del pasaporte')} value={country} set={setCountry}/><Field label={L('Passport reference / number','Référence / numéro du passeport','Referencia / número de pasaporte')} value={passportRef} set={setPassportRef} autoCapitalize="characters"/><Field label={L('Expiry date','Date d’expiration','Fecha de caducidad')} value={expires} set={setExpires} placeholder="YYYY-MM-DD"/><View style={s.note}><Text style={s.noteText}>{L('Do not enter information that is not requested. MediCrew may ask for additional proof later only if manual verification cannot be completed from the reference provided.','N’ajoutez aucune information non demandée. MediCrew pourra demander un justificatif supplémentaire uniquement si la vérification manuelle ne peut pas être faite à partir de la référence fournie.','No introduzcas información no solicitada. MediCrew podrá pedir una prueba adicional solo si la verificación manual no puede completarse con la referencia proporcionada.')}</Text></View><Pressable disabled={saving} onPress={submit} style={s.button}><Text style={s.buttonText}>{saving?L('Saving…','Enregistrement…','Guardando…'):L('Continue','Continuer','Continuar')}</Text></Pressable></View></ScrollView></SafeAreaView>}
function Field({label,value,set,placeholder,autoCapitalize='words'}:{label:string;value:string;set:(v:string)=>void;placeholder?:string;autoCapitalize?:any}){return <View style={s.field}><Text style={s.label}>{label}</Text><TextInput value={value} onChangeText={set} placeholder={placeholder} autoCapitalize={autoCapitalize} style={s.input}/></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.paper},container:{padding:24,paddingBottom:50},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:1.4,color:colors.pro},title:{fontSize:34,fontWeight:'900',color:colors.ink,marginTop:8},sub:{fontSize:13,lineHeight:20,color:colors.muted,marginTop:8},card:{marginTop:20,padding:18,borderWidth:1,borderColor:colors.line,borderRadius:radii.lg,backgroundColor:colors.white},field:{marginBottom:13},label:{fontSize:11,fontWeight:'800',color:colors.ink,marginBottom:6},input:{height:50,borderWidth:1,borderColor:colors.line,borderRadius:radii.md,paddingHorizontal:13,color:colors.ink,backgroundColor:colors.paper},note:{padding:12,borderRadius:radii.md,backgroundColor:colors.proSoft},noteText:{fontSize:10.5,lineHeight:16,color:colors.proDark},button:{height:54,borderRadius:radii.md,backgroundColor:colors.proDark,alignItems:'center',justifyContent:'center',marginTop:16},buttonText:{fontSize:14,fontWeight:'900',color:colors.white},error:{marginTop:15,padding:12,borderRadius:radii.md,backgroundColor:'#FDECEC'},errorText:{fontSize:12,color:'#A33A3A'}});