import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { colors, radii } from '../../lib/theme';
export default function Profile(){return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.container}><Pressable onPress={()=>router.back()}><Text style={styles.back}>‹ Back</Text></Pressable><View style={styles.header}><View style={styles.avatar}><Text style={styles.avatarText}>DR</Text></View><View style={styles.headText}><Text style={styles.name}>Dr. Alex Martin</Text><Text style={styles.role}>Doctor · Emergency Medicine</Text><View style={styles.verified}><Text style={styles.verifiedText}>✓ VERIFIED PROFESSIONAL</Text></View></View></View><Card title="Professional details"><Row label="Experience" value="8 years"/><Row label="Transport experience" value="24 missions"/><Row label="Air transport" value="12 missions"/><Row label="International" value="Yes"/></Card><Card title="Clinical skills"><Skill name="ICU / Critical Care" level="Advanced"/><Skill name="Mechanical ventilation" level="Advanced"/><Skill name="Central line management" level="Advanced"/><Skill name="ECMO" level="Experienced"/></Card><Card title="Languages"><Text style={styles.languages}>French · Native</Text><Text style={styles.languages}>English · Professional</Text><Text style={styles.languages}>Spanish · Professional</Text></Card><Pressable style={styles.secondary} onPress={()=>router.push('/professional/skills')}><Text style={styles.secondaryText}>Manage skills & certifications</Text></Pressable><Pressable style={styles.secondary} onPress={()=>router.push('/availability')}><Text style={styles.secondaryText}>Manage availability</Text></Pressable></ScrollView></SafeAreaView>}
function Card({title,children}:{title:string;children:React.ReactNode}){return <View style={styles.card}><Text style={styles.cardTitle}>{title}</Text>{children}</View>}
function Row({label,value}:{label:string;value:string}){return <View style={styles.row}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{value}</Text></View>}
function Skill({name,level}:{name:string;level:string}){return <View style={styles.skill}><Text style={styles.skillName}>{name}</Text><Text style={styles.level}>{level}</Text></View>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.paper},container:{padding:24,paddingBottom:40},back:{fontSize:16,fontWeight:'800',color:colors.ink,marginBottom:25},header:{flexDirection:'row',alignItems:'center'},avatar:{width:64,height:64,borderRadius:32,backgroundColor:colors.ink,alignItems:'center',justifyContent:'center'},avatarText:{fontSize:18,fontWeight:'900',color:colors.white},headText:{marginLeft:14,flex:1},name:{fontSize:23,fontWeight:'800',color:colors.ink},role:{fontSize:13,color:colors.muted,marginTop:3},verified:{alignSelf:'flex-start',marginTop:8,paddingHorizontal:8,paddingVertical:5,borderRadius:radii.pill,backgroundColor:colors.greenSoft},verifiedText:{fontSize:8,fontWeight:'900',letterSpacing:.7,color:colors.green},card:{backgroundColor:colors.white,borderWidth:1,borderColor:colors.line,borderRadius:radii.lg,padding:18,marginTop:18},cardTitle:{fontSize:17,fontWeight:'800',color:colors.ink,marginBottom:12},row:{flexDirection:'row',justifyContent:'space-between',paddingVertical:7},label:{fontSize:13,color:colors.muted},value:{fontSize:13,fontWeight:'800',color:colors.ink},skill:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',paddingVertical:10,borderBottomWidth:1,borderBottomColor:colors.line},skillName:{fontSize:13,fontWeight:'700',color:colors.ink,flex:1},level:{fontSize:11,fontWeight:'800',color:colors.green},languages:{fontSize:14,color:colors.ink,paddingVertical:6},secondary:{height:54,borderRadius:radii.md,borderWidth:1,borderColor:colors.line,backgroundColor:colors.white,alignItems:'center',justifyContent:'center',marginTop:12},secondaryText:{fontSize:14,fontWeight:'800',color:colors.ink}});
