import { useEffect,useState } from 'react';
import { ActivityIndicator,Alert,Image,Pressable,ScrollView,StyleSheet,Text,View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { colors,radii } from '../../lib/theme';
import { supabase } from '../../lib/supabase';
import { avatarUrl,chooseAndUploadAvatar } from '../../lib/avatar';
import { usePreferences } from '../../lib/preferences-context';
import { confirmAccountDeletion } from '../../lib/account-actions';

export default function Profile(){
 const prefs=usePreferences();const[loading,setLoading]=useState(true),[profile,setProfile]=useState<any>(null),[pro,setPro]=useState<any>(null),[uploading,setUploading]=useState(false);
 useEffect(()=>{void load()},[]);
 async function load(){if(!supabase){setLoading(false);return}const{data:{user}}=await supabase.auth.getUser();if(!user){setLoading(false);return}const[{data:p,error:pe},{data:r,error:re}]=await Promise.all([supabase.from('profiles').select('first_name,last_name,email,phone,avatar_url,headline,bio,city,country').eq('id',user.id).maybeSingle(),supabase.from('professionals').select('professional_type,nationality,years_experience,license_country,license_authority,verification_status,base_city,base_airport_code,country_of_operation').eq('id',user.id).maybeSingle()]);if(pe||re)Alert.alert('Profile unavailable',(pe||re)?.message||'Unknown error');else{setProfile(p);setPro(r)}setLoading(false)}
 async function upload(){if(!supabase)return;setUploading(true);try{const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Session expired');const path=await chooseAndUploadAvatar(user.id,profile?.avatar_url||null);if(path)setProfile((x:any)=>({...x,avatar_url:path}))}catch(e:any){Alert.alert('Photo upload failed',e?.message||'Unable to update photo')}finally{setUploading(false)}}
 async function logout(){if(!supabase)return;await supabase.auth.signOut();router.replace('/auth')}
 if(loading)return <SafeAreaView style={s.safe}><ActivityIndicator style={{marginTop:80}} size="large" color={colors.pro}/></SafeAreaView>;
 const full=[profile?.first_name,profile?.last_name].filter(Boolean).join(' ')||prefs.tr('professional'),photo=avatarUrl(profile?.avatar_url);const profession=pro?.professional_type==='nurse'?prefs.tr('nurse'):prefs.tr('doctor');
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.container}><Pressable onPress={()=>router.back()}><Text style={s.back}>‹ {prefs.tr('back')}</Text></Pressable><View style={s.header}>{photo?<Image source={{uri:photo}} style={s.avatar}/>:<View style={[s.avatar,s.fallback]}><Text style={s.initial}>{full.slice(0,2).toUpperCase()}</Text></View>}<View style={{flex:1}}><Text style={s.name}>{full}</Text><Text style={s.headline}>{profile?.headline||`${profession} · ${pro?.years_experience||0} years experience`}</Text><Text style={s.location}>{[pro?.base_city,pro?.base_airport_code].filter(Boolean).join(' · ')}</Text></View></View><View style={[s.verified,pro?.verification_status!=='verified'&&s.pending]}><Text style={[s.verifiedText,pro?.verification_status!=='verified'&&s.pendingText]}>{pro?.verification_status==='verified'?'✓ VERIFIED PROFESSIONAL':String(pro?.verification_status||'pending').toUpperCase()}</Text></View>{profile?.bio?<Text style={s.bio}>{profile.bio}</Text>:null}<Pressable disabled={uploading} onPress={upload} style={s.photoButton}><Text style={s.photoButtonText}>{uploading?'Uploading…':'Change profile photo'}</Text></Pressable><View style={s.card}><Text style={s.cardTitle}>Professional profile</Text><Row label="Profession" value={profession}/><Row label="Experience" value={`${pro?.years_experience||0} years`}/><Row label="Nationality" value={pro?.nationality||'—'}/><Row label="Base city" value={pro?.base_city||'—'}/><Row label="Base airport" value={pro?.base_airport_code||'—'}/><Row label="Licence jurisdiction" value={pro?.license_country||'—'}/><Row label="Issuing authority" value={pro?.license_authority||'—'}/></View><View style={s.card}><Text style={s.cardTitle}>Contact</Text><Row label="Public email" value={profile?.email||'—'}/><Row label="Phone" value={profile?.phone||'—'}/></View><Pressable onPress={()=>router.push('/preferences' as never)} style={s.secondary}><Text style={s.secondaryText}>{prefs.tr('settings')}</Text></Pressable><Pressable onPress={()=>router.push('/professional/edit')} style={s.primary}><Text style={s.primaryText}>Edit public profile & base</Text></Pressable><Pressable onPress={()=>router.push('/availability')} style={s.secondary}><Text style={s.secondaryText}>Availability calendar</Text></Pressable><Pressable onPress={()=>confirmAccountDeletion(()=>router.replace('/'))} style={s.logout}><Text style={s.logoutText}>Delete account</Text></Pressable><Pressable onPress={logout} style={s.logout}><Text style={s.logoutText}>Log out</Text></Pressable></ScrollView></SafeAreaView>}
function Row({label,value}:{label:string;value:string}){return <View style={s.row}><Text style={s.label}>{label}</Text><Text style={s.value}>{value}</Text></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.paper},container:{flexGrow:1,padding:22,paddingBottom:45},back:{fontSize:15,fontWeight:'800',color:colors.ink,marginBottom:23},header:{flexDirection:'row',gap:14,alignItems:'center'},avatar:{width:78,height:78,borderRadius:25},fallback:{backgroundColor:colors.proSoft,alignItems:'center',justifyContent:'center'},initial:{fontSize:18,fontWeight:'900',color:colors.proDark},name:{fontSize:24,fontWeight:'900',color:colors.ink},headline:{fontSize:12.5,color:colors.ink,marginTop:4},location:{fontSize:11,color:colors.muted,marginTop:4},verified:{alignSelf:'flex-start',marginTop:14,paddingHorizontal:9,paddingVertical:6,borderRadius:99,backgroundColor:colors.proSoft},verifiedText:{fontSize:8,fontWeight:'900',letterSpacing:.7,color:colors.proDark},pending:{backgroundColor:colors.line},pendingText:{color:colors.muted},bio:{fontSize:13,lineHeight:20,color:colors.muted,marginTop:15},photoButton:{height:44,borderWidth:1,borderColor:colors.line,borderRadius:radii.md,backgroundColor:colors.white,alignItems:'center',justifyContent:'center',marginTop:13},photoButtonText:{fontSize:12,fontWeight:'800',color:colors.ink},card:{padding:17,borderWidth:1,borderColor:colors.line,borderRadius:radii.lg,backgroundColor:colors.white,marginTop:14},cardTitle:{fontSize:16,fontWeight:'900',color:colors.ink,marginBottom:9},row:{flexDirection:'row',justifyContent:'space-between',gap:14,paddingVertical:8,borderBottomWidth:1,borderBottomColor:colors.line},label:{fontSize:11.5,color:colors.muted},value:{flex:1,fontSize:11.5,fontWeight:'800',color:colors.ink,textAlign:'right'},primary:{height:54,borderRadius:radii.md,backgroundColor:colors.proDark,alignItems:'center',justifyContent:'center',marginTop:9},primaryText:{fontSize:13,fontWeight:'900',color:colors.white},secondary:{height:50,borderRadius:radii.md,borderWidth:1,borderColor:colors.line,backgroundColor:colors.white,alignItems:'center',justifyContent:'center',marginTop:8},secondaryText:{fontSize:12.5,fontWeight:'800',color:colors.ink},logout:{height:50,borderRadius:radii.md,borderWidth:1,borderColor:'#E4B4B4',backgroundColor:'#FFF7F7',alignItems:'center',justifyContent:'center',marginTop:8},logoutText:{fontSize:13,fontWeight:'900',color:'#A33A3A'}});
