import { useState } from 'react';
import { ActivityIndicator,Alert,Pressable,ScrollView,StyleSheet,Text,TextInput,View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { colors,radii } from '../../lib/theme';
import { supabase } from '../../lib/supabase';
import { usePreferences } from '../../lib/preferences-context';
import { localize } from '../../lib/i18n';

export default function Verification(){
 const prefs=usePreferences();const L=(en:string,fr:string,es:string)=>localize(prefs.language,en,fr,es);
 const[licenceRef,setLicenceRef]=useState(''),[diplomaRef,setDiplomaRef]=useState(''),[licenceExpiry,setLicenceExpiry]=useState(''),[saving,setSaving]=useState(false),[error,setError]=useState('');
 async function submit(){if(!supabase)return;setError('');if(!licenceRef.trim()||!diplomaRef.trim())return setError(L('Professional registration and diploma references are required.','Les références d’inscription professionnelle et de diplôme sont requises.','Las referencias de registro profesional y diploma son obligatorias.'));if(licenceExpiry.trim()&&!/^\d{4}-\d{2}-\d{2}$/.test(licenceExpiry.trim()))return setError('YYYY-MM-DD');setSaving(true);try{const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error(L('Session expired','Session expirée','Sesión caducada'));const pro=await supabase.from('professionals').select('license_authority,license_country,license_number').eq('id',user.id).maybeSingle();if(pro.error)throw pro.error;if(!pro.data?.license_number||!pro.data?.license_country||!pro.data?.license_authority)throw new Error(L('Professional registration details are incomplete.','Les informations d’inscription professionnelle sont incomplètes.','Los datos de registro profesional están incompletos.'));const rows=[{professional_id:user.id,document_type:'rpps',title:`Professional registration · ${pro.data.license_authority}`,reference:licenceRef.trim(),expires_at:licenceExpiry.trim()||null,status:'pending'},{professional_id:user.id,document_type:'diploma',title:'Medical / nursing diploma reference',reference:diplomaRef.trim(),expires_at:null,status:'pending'}];for(const row of rows){const existing=await supabase.from('professional_documents').select('id').eq('professional_id',user.id).eq('document_type',row.document_type).eq('status','pending').limit(1);if(existing.error)throw existing.error;if(existing.data?.[0]){const u=await supabase.from('professional_documents').update(row).eq('id',existing.data[0].id);if(u.error)throw u.error}else{const i=await supabase.from('professional_documents').insert(row);if(i.error)throw i.error}}const review=await supabase.rpc('submit_my_account_for_review');if(review.error)throw review.error;Alert.alert(L('Profile submitted','Profil envoyé','Perfil enviado'),L('Your profile has been created. The MediCrew team will verify the official references you provided and email you when the review is complete. Review can take up to 24 hours.','Votre profil a été créé. L’équipe MediCrew vérifiera les références officielles fournies et vous enverra un email à la fin de l’analyse. Cela peut prendre jusqu’à 24 h.','Tu perfil ha sido creado. El equipo de MediCrew verificará las referencias oficiales y te enviará un correo cuando finalice la revisión. Puede tardar hasta 24 h.'),[{text:'OK',onPress:()=>router.replace('/pending-review' as never)}])}catch(e:any){setError(e?.message||'MediCrew')}finally{setSaving(false)}}
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.container} keyboardShouldPersistTaps="handled"><Text style={s.eyebrow}>{L('PROFESSIONAL VERIFICATION · 2/2','VÉRIFICATION PROFESSIONNELLE · 2/2','VERIFICACIÓN PROFESIONAL · 2/2')}</Text><Text style={s.title}>{L('Official references.','Références officielles.','Referencias oficiales.')}</Text><Text style={s.sub}>{L('MediCrew verifies doctors and nurses using official registration and diploma references. These fields are private and never displayed publicly.','MediCrew vérifie les médecins et infirmiers grâce aux références officielles d’inscription et de diplôme. Ces informations restent privées et ne sont jamais affichées publiquement.','MediCrew verifica médicos y enfermeros mediante referencias oficiales de registro y diploma. Estos datos son privados y nunca se muestran públicamente.')}</Text>{error?<View style={s.error}><Text style={s.errorText}>{error}</Text></View>:null}<View style={s.card}><Text style={s.cardTitle}>{L('Professional registration','Inscription professionnelle','Registro profesional')}</Text><Field label={L('Official registration / licence reference','Référence officielle de licence / inscription','Referencia oficial de licencia / registro')} value={licenceRef} set={setLicenceRef}/><Field label={L('Expiry date (if applicable)','Date d’expiration (si applicable)','Fecha de caducidad (si aplica)')} value={licenceExpiry} set={setLicenceExpiry} placeholder="YYYY-MM-DD"/></View><View style={s.card}><Text style={s.cardTitle}>{L('Diploma','Diplôme','Diploma')}</Text><Field label={L('Diploma number / official reference','Numéro de diplôme / référence officielle','Número de diploma / referencia oficial')} value={diplomaRef} set={setDiplomaRef}/><View style={s.note}><Text style={s.noteText}>{L('If a reference cannot be independently verified, MediCrew may contact you for additional proof before approving the account.','Si une référence ne peut pas être vérifiée indépendamment, MediCrew pourra vous demander un justificatif complémentaire avant validation.','Si una referencia no puede verificarse de forma independiente, MediCrew podrá pedir una prueba adicional antes de aprobar la cuenta.')}</Text></View></View><Pressable disabled={saving} onPress={submit} style={s.button}>{saving?<ActivityIndicator color={colors.white}/>:<Text style={s.buttonText}>{L('Submit for verification','Envoyer pour vérification','Enviar para verificación')}</Text>}</Pressable></ScrollView></SafeAreaView>}
function Field({label,value,set,placeholder}:{label:string;value:string;set:(v:string)=>void;placeholder?:string}){return <View style={s.field}><Text style={s.label}>{label}</Text><TextInput value={value} onChangeText={set} placeholder={placeholder} autoCapitalize="characters" style={s.input}/></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.paper},container:{padding:24,paddingBottom:50},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:1.4,color:colors.pro},title:{fontSize:34,fontWeight:'900',color:colors.ink,marginTop:8},sub:{fontSize:13,lineHeight:20,color:colors.muted,marginTop:8},card:{marginTop:18,padding:18,borderWidth:1,borderColor:colors.line,borderRadius:radii.lg,backgroundColor:colors.white},cardTitle:{fontSize:17,fontWeight:'900',color:colors.ink,marginBottom:8},field:{marginBottom:13},label:{fontSize:11,fontWeight:'800',color:colors.ink,marginBottom:6},input:{height:50,borderWidth:1,borderColor:colors.line,borderRadius:radii.md,paddingHorizontal:13,color:colors.ink,backgroundColor:colors.paper},note:{padding:12,borderRadius:radii.md,backgroundColor:colors.proSoft},noteText:{fontSize:10.5,lineHeight:16,color:colors.proDark},button:{height:54,borderRadius:radii.md,backgroundColor:colors.proDark,alignItems:'center',justifyContent:'center',marginTop:18},buttonText:{fontSize:14,fontWeight:'900',color:colors.white},error:{marginTop:15,padding:12,borderRadius:radii.md,backgroundColor:'#FDECEC'},errorText:{fontSize:12,color:'#A33A3A'}});