import { useEffect, useState } from 'react';
import { Alert, SafeAreaView, ScrollView, StyleSheet, Text, TouchableOpacity, View, ActivityIndicator } from 'react-native';
import { supabase } from '../lib/supabase';
import { colors } from '../lib/theme';
const C=colors;
export default function Admin(){const [loading,setLoading]=useState(true);const [companies,setCompanies]=useState<any[]>([]);const [professionals,setProfessionals]=useState<any[]>([]);const [error,setError]=useState('');
const load=async()=>{if(!supabase)return;setLoading(true);const [co,pr]=await Promise.all([supabase.from('companies').select('id,company_name,organization_type,verification_status,created_at').order('created_at',{ascending:false}),supabase.from('professionals').select('id,professional_type,specialty,verification_status,years_experience,created_at').order('created_at',{ascending:false})]);if(co.error||pr.error)setError(co.error?.message||pr.error?.message||'Could not load admin data');else{setCompanies(co.data||[]);setProfessionals(pr.data||[])}setLoading(false)};
useEffect(()=>{load()},[]);
const update=async(type:'company'|'professional',id:string,status:'verified'|'rejected')=>{if(!supabase)return;const rpc=type==='company'?'admin_verify_company':'admin_verify_professional';const args=type==='company'?{p_company_id:id,p_status:status}:{p_professional_id:id,p_status:status};const {error}=await supabase.rpc(rpc,args);if(error)Alert.alert('Action failed',error.message);else load()};
return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.container}><Text style={s.eyebrow}>MEDICREW · ADMIN</Text><Text style={s.title}>Operations.</Text><Text style={s.subtitle}>Verify the network, manage risk and keep the marketplace trustworthy.</Text>{error?<View style={s.error}><Text style={s.errorText}>{error}</Text></View>:null}{loading?<ActivityIndicator color={C.green} size="large"/>:<><View style={s.stats}><Stat value={`${companies.filter(x=>x.verification_status==='pending').length}`} label="companies pending"/><Stat value={`${professionals.filter(x=>x.verification_status==='pending').length}`} label="professionals pending"/><Stat value={`${companies.filter(x=>x.verification_status==='verified').length}`} label="verified companies"/></View><Text style={s.sectionTitle}>Company verification</Text>{companies.filter(x=>x.verification_status==='pending').map(x=><View style={s.card} key={x.id}><Text style={s.name}>{x.company_name}</Text><Text style={s.meta}>{x.organization_type||'Organization'} · Pending</Text><View style={s.actions}><TouchableOpacity style={s.reject} onPress={()=>update('company',x.id,'rejected')}><Text style={s.rejectText}>Reject</Text></TouchableOpacity><TouchableOpacity style={s.verify} onPress={()=>update('company',x.id,'verified')}><Text style={s.verifyText}>Verify company</Text></TouchableOpacity></View></View>)}<Text style={[s.sectionTitle,{marginTop:22}]}>Professional verification</Text>{professionals.filter(x=>x.verification_status==='pending').map(x=><View style={s.card} key={x.id}><Text style={s.name}>{x.professional_type==='doctor'?'Doctor':'Nurse'} · {x.specialty||'Specialty not provided'}</Text><Text style={s.meta}>{x.years_experience} years experience · Pending</Text><View style={s.actions}><TouchableOpacity style={s.reject} onPress={()=>update('professional',x.id,'rejected')}><Text style={s.rejectText}>Reject</Text></TouchableOpacity><TouchableOpacity style={s.verify} onPress={()=>update('professional',x.id,'verified')}><Text style={s.verifyText}>Verify professional</Text></TouchableOpacity></View></View>)}</>}</ScrollView></SafeAreaView>}
function Stat({value,label}:{value:string;label:string}){return <View style={s.stat}><Text style={s.statValue}>{value}</Text><Text style={s.statLabel}>{label}</Text></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:C.paper},container:{padding:22,paddingBottom:50},eyebrow:{color:C.green,fontWeight:'800',fontSize:11,letterSpacing:1.5},title:{fontSize:32,fontWeight:'800',color:C.ink,letterSpacing:-1,marginTop:7},subtitle:{color:C.muted,fontSize:13,lineHeight:19,marginTop:7,marginBottom:20},stats:{flexDirection:'row',backgroundColor:C.white,borderWidth:1,borderColor:C.line,borderRadius:18,paddingVertical:16,marginBottom:25},stat:{flex:1,paddingHorizontal:10},statValue:{fontSize:22,fontWeight:'900',color:C.ink},statLabel:{fontSize:10,color:C.muted,marginTop:3},sectionTitle:{fontSize:18,fontWeight:'800',color:C.ink,marginBottom:10},card:{backgroundColor:C.white,borderWidth:1,borderColor:C.line,borderRadius:16,padding:16,marginBottom:10},name:{fontSize:15,fontWeight:'800',color:C.ink},meta:{fontSize:12,color:C.muted,marginTop:4},actions:{flexDirection:'row',gap:9,marginTop:14},reject:{flex:1,height:43,borderWidth:1,borderColor:'#E7CACA',borderRadius:11,alignItems:'center',justifyContent:'center'},rejectText:{color:'#A83E3E',fontWeight:'800'},verify:{flex:2,height:43,backgroundColor:C.ink,borderRadius:11,alignItems:'center',justifyContent:'center'},verifyText:{color:C.white,fontWeight:'800'},error:{backgroundColor:'#FDECEC',borderRadius:12,padding:12,marginBottom:14},errorText:{color:'#B83D3D',fontSize:12}});
