import { useEffect, useState } from 'react';
import { ActivityIndicator, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { supabase } from '../lib/supabase';
import { colors, radii } from '../lib/theme';

type Message={id:string;sender_id:string;body:string;created_at:string};
export default function Chat(){
 const {missionId}=useLocalSearchParams<{missionId:string}>(); const [messages,setMessages]=useState<Message[]>([]); const [text,setText]=useState(''); const [loading,setLoading]=useState(true); const [sending,setSending]=useState(false); const [error,setError]=useState('');
 const load=async()=>{if(!supabase||!missionId)return; setLoading(true); const {data:conv}=await supabase.from('conversations').select('id,missions(title)').eq('mission_id',missionId).maybeSingle(); if(!conv){setError('Mission chat is not available yet.');setLoading(false);return;} const {data,error:e}=await supabase.from('messages').select('id,sender_id,body,created_at').eq('conversation_id',conv.id).order('created_at',{ascending:true}); if(e)setError(e.message); else setMessages((data||[]) as Message[]); await supabase.rpc('mark_conversation_read',{p_conversation_id:conv.id}); setLoading(false); return conv.id;};
 useEffect(()=>{let channel:any; load().then(async convId=>{if(!convId||!supabase)return; channel=supabase.channel(`mission-chat-${convId}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'messages',filter:`conversation_id=eq.${convId}`},payload=>{setMessages(prev=>prev.some(m=>m.id===payload.new.id)?prev:[...prev,payload.new as Message]);}).subscribe();}); return()=>{if(channel&&supabase)supabase.removeChannel(channel)};},[missionId]);
 const send=async()=>{if(!supabase||!missionId||!text.trim()||sending)return; setSending(true);setError(''); const body=text.trim(); setText(''); const {error:e}=await supabase.rpc('send_mission_message',{p_mission_id:missionId,p_body:body}); if(e){setText(body);setError(e.message);} setSending(false);};
 return <SafeAreaView style={s.safe}><KeyboardAvoidingView style={s.flex} behavior={Platform.OS==='ios'?'padding':undefined}><View style={s.header}><Pressable onPress={()=>router.back()}><Text style={s.back}>‹ Back</Text></Pressable><View style={s.headerCenter}><Text style={s.eyebrow}>MISSION CHAT</Text><Text style={s.title}>Secure coordination</Text></View><View style={s.lock}><Text>🔒</Text></View></View><Text style={s.notice}>Operational communication only. Do not share patient-identifying or clinical information here.</Text>{error?<View style={s.error}><Text style={s.errorText}>{error}</Text></View>:null}<ScrollView contentContainerStyle={s.messages} ref={r=>r?.scrollToEnd({animated:false})}>{loading?<ActivityIndicator color={colors.green}/>:messages.length===0?<Text style={s.empty}>No messages yet. Start the mission coordination here.</Text>:messages.map(m=><MessageBubble key={m.id} message={m}/>)}</ScrollView><View style={s.composer}><TextInput value={text} onChangeText={setText} placeholder="Write a coordination message…" placeholderTextColor="#929995" style={s.input} multiline maxLength={4000}/><Pressable disabled={!text.trim()||sending} onPress={send} style={[s.send,(!text.trim()||sending)&&s.disabled]}><Text style={s.sendText}>{sending?'…':'↑'}</Text></Pressable></View></KeyboardAvoidingView></SafeAreaView>;
}
function MessageBubble({message}:{message:Message}){const [mine,setMine]=useState(false); useEffect(()=>{supabase?.auth.getUser().then(({data})=>setMine(data.user?.id===message.sender_id))},[message.sender_id]); return <View style={[s.bubbleRow,mine&&s.mineRow]}><View style={[s.bubble,mine?s.mine:s.theirs]}><Text style={[s.body,mine&&s.mineBody]}>{message.body}</Text><Text style={[s.time,mine&&s.mineTime]}>{new Date(message.created_at).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</Text></View></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.paper},flex:{flex:1},header:{padding:18,borderBottomWidth:1,borderBottomColor:colors.line,flexDirection:'row',alignItems:'center'},back:{fontSize:16,fontWeight:'800',color:colors.ink},headerCenter:{flex:1,alignItems:'center'},eyebrow:{fontSize:9,fontWeight:'900',letterSpacing:1.2,color:colors.green},title:{fontSize:15,fontWeight:'800',color:colors.ink,marginTop:3},lock:{width:35,height:35,borderRadius:18,backgroundColor:colors.greenSoft,alignItems:'center',justifyContent:'center'},notice:{margin:14,padding:11,borderRadius:radii.md,backgroundColor:'#FFF8E8',color:'#7A5D20',fontSize:11,lineHeight:16},messages:{padding:16,paddingBottom:20,flexGrow:1,justifyContent:'flex-end'},empty:{textAlign:'center',color:colors.muted,fontSize:13,padding:30},bubbleRow:{flexDirection:'row',marginVertical:4},mineRow:{justifyContent:'flex-end'},bubble:{maxWidth:'82%',paddingHorizontal:13,paddingVertical:10,borderRadius:16},theirs:{backgroundColor:colors.white,borderWidth:1,borderColor:colors.line,borderBottomLeftRadius:5},mine:{backgroundColor:colors.ink,borderBottomRightRadius:5},body:{color:colors.ink,fontSize:14,lineHeight:20},mineBody:{color:colors.white},time:{fontSize:9,color:colors.muted,marginTop:4},mineTime:{color:'#B9C0BC',textAlign:'right'},composer:{padding:10,borderTopWidth:1,borderTopColor:colors.line,backgroundColor:colors.white,flexDirection:'row',alignItems:'flex-end'},input:{flex:1,minHeight:44,maxHeight:110,borderWidth:1,borderColor:colors.line,borderRadius:16,paddingHorizontal:14,paddingVertical:10,fontSize:14,color:colors.ink,backgroundColor:colors.paper},send:{marginLeft:8,width:44,height:44,borderRadius:22,backgroundColor:colors.ink,alignItems:'center',justifyContent:'center'},sendText:{fontSize:20,color:colors.green,fontWeight:'900'},disabled:{opacity:.35},error:{marginHorizontal:14,padding:10,borderRadius:10,backgroundColor:'#FFEDEC'},errorText:{color:'#A23A32',fontSize:12}});
