import { useEffect, useState } from 'react';
import { router, useLocalSearchParams } from 'expo-router';
import { ScrollView, StyleSheet, Text, TouchableOpacity, View, ActivityIndicator } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { supabase } from '../lib/supabase';
const C={bg:'#F7F8F6',ink:'#101214',muted:'#6F7672',green:'#18B889',soft:'#DDF5ED',white:'#FFF',line:'#E5E8E5',red:'#B83D3D'};
type Candidate={match_id:string;professional_id:string;first_name:string;last_name:string;professional_type:'doctor'|'nurse';specialty:string|null;years_experience:number;medical_transport_years:number;air_ambulance_years:number;verification_status:string;score:number;eligible:boolean;reasons:string[]};
export default function CompanyCandidates(){const {missionId}=useLocalSearchParams<{missionId:string}>();const [items,setItems]=useState<Candidate[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [selecting,setSelecting]=useState('');const load=async()=>{if(!missionId||!supabase)return;setLoading(true);const {data,error}=await supabase.rpc('company_mission_matches',{p_mission_id:missionId});if(error)setError(error.message);else setItems((data||[]) as Candidate[]);setLoading(false)};useEffect(()=>{load()},[missionId]);const select=async(id:string)=>{if(!supabase||!missionId)return;setSelecting(id);setError('');const {error}=await supabase.rpc('select_mission_professional',{p_mission_id:missionId,p_professional_id:id});if(error)setError(error.message);else router.replace({pathname:'/mission-confirmed',params:{missionId}});setSelecting('')};return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.container}><TouchableOpacity onPress={()=>router.back()}><Text style={s.back}>‹ Back</Text></TouchableOpacity><Text style={s.eyebrow}>MATCHING</Text><Text style={s.title}>Best-fit professionals.</Text><Text style={s.subtitle}>Only eligible, verified matches are shown to the company.</Text>{error?<View style={s.error}><Text style={s.errorText}>{error}</Text></View>:null}{loading?<ActivityIndicator size="large" color={C.green}/>:items.length===0?<View style={s.empty}><Text style={s.emptyTitle}>No eligible matches yet</Text><Text style={s.emptyText}>Matching depends on verification, profession, requirements and availability.</Text></View>:items.map(c=><View key={c.match_id} style={s.card}><View style={s.top}><View style={s.initial}><Text style={s.initialText}>{c.first_name?.[0]}{c.last_name?.[0]}</Text></View><View style={s.identity}><Text style={s.name}>{c.first_name} {c.last_name}</Text><Text style={s.meta}>{c.professional_type==='nurse'?'Nurse':'Doctor'}{c.specialty?` · ${c.specialty}`:''}</Text></View><View style={s.score}><Text style={s.scoreNum}>{Math.round(c.score)}%</Text><Text style={s.scoreLabel}>MATCH</Text></View></View><View style={s.stats}><Stat value={`${c.years_experience}y`} label="experience"/><Stat value={`${c.medical_transport_years}y`} label="transport"/><Stat value={`${c.air_ambulance_years}y`} label="air"/></View><View style={s.reasons}>{c.reasons.map(r=><Text key={r} style={s.reason}>✓ {r}</Text>)}</View><TouchableOpacity disabled={!!selecting} style={s.select} onPress={()=>select(c.professional_id)}>{selecting===c.professional_id?<ActivityIndicator color={C.white}/>:<Text style={s.selectText}>Select professional</Text>}</TouchableOpacity></View>)}</ScrollView></SafeAreaView>}
function Stat({value,label}:{value:string;label:string}){return <View style={s.stat}><Text style={s.statValue}>{value}</Text><Text style={s.statLabel}>{label}</Text></View>};
const s=StyleSheet.create({safe:{flex:1,backgroundColor:C.bg},container:{padding:22,paddingBottom:50},back:{color:C.ink,fontWeight:'700',fontSize:14,marginBottom:24},eyebrow:{color:C.green,fontWeight:'800',fontSize:11,letterSpacing:1.5},title:{fontSize:30,fontWeight:'800',color:C.ink,letterSpacing:-.8,marginTop:7},subtitle:{color:C.muted,fontSize:13,lineHeight:19,marginTop:7,marginBottom:20},error:{backgroundColor:'#FDECEC',borderRadius:12,padding:12,marginBottom:12},errorText:{color:C.red,fontSize:12},empty:{backgroundColor:C.white,borderWidth:1,borderColor:C.line,borderRadius:18,padding:25,alignItems:'center'},emptyTitle:{fontSize:17,fontWeight:'800',color:C.ink},emptyText:{fontSize:13,color:C.muted,textAlign:'center',lineHeight:19,marginTop:6},card:{backgroundColor:C.white,borderWidth:1,borderColor:C.line,borderRadius:18,padding:17,marginBottom:12},top:{flexDirection:'row',alignItems:'center'},initial:{width:48,height:48,borderRadius:24,backgroundColor:C.ink,alignItems:'center',justifyContent:'center'},initialText:{color:C.green,fontWeight:'800'},identity:{flex:1,marginLeft:12},name:{fontSize:16,fontWeight:'800',color:C.ink},meta:{fontSize:12,color:C.muted,marginTop:4},score:{alignItems:'flex-end'},scoreNum:{fontSize:20,fontWeight:'900',color:C.green},scoreLabel:{fontSize:8,fontWeight:'800',color:C.muted,letterSpacing:1},stats:{flexDirection:'row',borderTopWidth:1,borderBottomWidth:1,borderColor:C.line,marginVertical:14,paddingVertical:11},stat:{flex:1},statValue:{fontSize:15,fontWeight:'800',color:C.ink},statLabel:{fontSize:10,color:C.muted,marginTop:2},reasons:{gap:5,marginBottom:14},reason:{fontSize:12,color:'#3E5C51'},select:{height:46,borderRadius:12,backgroundColor:C.ink,alignItems:'center',justifyContent:'center'},selectText:{color:C.white,fontWeight:'800',fontSize:13}});
