import { useState } from 'react';
import { ActivityIndicator,Alert,Pressable,ScrollView,StyleSheet,Text,TextInput,View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { colors,radii } from '../lib/theme';
import { supabase } from '../lib/supabase';
import { usePreferences } from '../lib/preferences-context';
import { localize } from '../lib/i18n';

export default function CompanyVerification(){
 const prefs=usePreferences();const L=(en:string,fr:string,es:string)=>localize(prefs.language,en,fr,es);
 const[reference,setReference]=useState(''),[authority,setAuthority]=useState(''),[saving,setSaving]=useState(false),[error,setError]=useState('');
 async function submit(){if(!supabase)return;setError('');if(!reference.trim()||!authority.trim())return setError(L('Official registration reference and registry authority are required.','La référence officielle et l’autorité du registre sont requises.','La referencia oficial y la autoridad del registro son obligatorias.'));setSaving(true);try{const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error(L('Session expired','Session expirée','Sesión caducada'));const company=await supabase.from('companies').select('registration_country,registration_number,company_name').eq('id',user.id).maybeSingle();if(company.error)throw company.error;if(!company.data?.registration_country||!company.data?.registration_number)throw new Error(L('Organization registration details are incomplete.','Les informations d’immatriculation sont incomplètes.','Los datos de registro de la organización están incompletos.'));const existing=await supabase.from('company_verification_documents').select('id').eq('company_id',user.id).eq('document_type','company_registration').eq('status','pending').limit(1);if(existing.error)throw existing.error;const row={company_id:user.id,document_type:'company_registration',title:`${authority.trim()} · ${company.data.company_name||'Organization'}`,reference:reference.trim(),status:'pending'};if(existing.data?.[0]){const u=await supabase.from('company_verification_documents').update(row).eq('id',existing.data[0].id);if(u.error)throw u.error}else{const i=await supabase.from('company_verification_documents').insert(row);if(i.error)throw i.error}const review=await supabase.rpc('submit_my_account_for_review');if(review.error)throw review.error;Alert.alert(L('Profile submitted','Profil envoyé','Perfil enviado'),L('Your organization profile has been created. The MediCrew team will verify the official registry information and email you when the review is complete. Review can take up to 24 hours.','Votre profil entreprise a été créé. L’équipe MediCrew vérifiera les informations officielles du registre et vous enverra un email lorsque l’analyse sera terminée. Cela peut prendre jusqu’à 24 h.','Tu perfil de empresa ha sido creado. El equipo de MediCrew verificará la información oficial del registro y te enviará un correo cuando finalice la revisión. Puede tardar hasta 24 h.'),[{text:'OK',onPress:()=>router.replace('/pending-review' as never)}])}catch(e:any){setError(e?.message||'MediCrew')}finally{setSaving(false)}}
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.container} keyboardShouldPersistTaps="handled"><Text style={s.eyebrow}>{L('ORGANIZATION VERIFICATION','VÉRIFICATION ENTREPRISE','VERIFICACIÓN DE EMPRESA')}</Text><Text style={s.title}>{L('Official registry check.','Vérification du registre officiel.','Verificación del registro oficial.')}</Text><Text style={s.sub}>{L('MediCrew uses official registry references instead of storing large company documents. Enter the information exactly as it appears in the public or official registry for your jurisdiction.','MediCrew utilise les références des registres officiels au lieu de stocker de gros documents. Saisissez les informations exactement comme elles apparaissent dans le registre public ou officiel de votre juridiction.','MediCrew usa referencias de registros oficiales en lugar de almacenar documentos pesados. Introduce la información exactamente como aparece en el registro público u oficial de tu jurisdicción.')}</Text>{error?<View style={s.error}><Text style={s.errorText}>{error}</Text></View>:null}<View style={s.card}><Field label={L('Registry / issuing authority','Registre / autorité émettrice','Registro / autoridad emisora')} value={authority} set={setAuthority} placeholder={L('e.g. national company registry','ex. registre national des entreprises','p. ej. registro nacional de empresas')}/><Field label={L('Official registration reference','Référence officielle d’immatriculation','Referencia oficial de registro')} value={reference} set={setReference} autoCapitalize="characters"/><View style={s.note}><Text style={s.noteText}>{L('The MediCrew team compares this reference with the organization details provided during signup. If the registry cannot be checked independently, additional proof may be requested before approval.','L’équipe MediCrew compare cette référence avec les informations fournies lors de l’inscription. Si le registre ne peut pas être vérifié indépendamment, un justificatif complémentaire pourra être demandé avant validation.','El equipo de MediCrew compara esta referencia con los datos de la organización. Si el registro no puede verificarse de forma independiente, se podrá solicitar una prueba adicional antes de aprobar la cuenta.')}</Text></View><Pressable disabled={saving} onPress={submit} style={s.button}>{saving?<ActivityIndicator color={colors.white}/>:<Text style={s.buttonText}>{L('Submit organization for verification','Envoyer l’organisation en vérification','Enviar organización para verificación')}</Text>}</Pressable></View></ScrollView></SafeAreaView>}
function Field({label,value,set,placeholder,autoCapitalize='words'}:{label:string;value:string;set:(v:string)=>void;placeholder?:string;autoCapitalize?:any}){return <View style={s.field}><Text style={s.label}>{label}</Text><TextInput value={value} onChangeText={set} placeholder={placeholder} autoCapitalize={autoCapitalize} style={s.input}/></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.paper},container:{padding:24,paddingBottom:50},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:1.4,color:colors.company},title:{fontSize:34,fontWeight:'900',color:colors.ink,marginTop:8},sub:{fontSize:13,lineHeight:20,color:colors.muted,marginTop:8},card:{marginTop:20,padding:18,borderWidth:1,borderColor:colors.line,borderRadius:radii.lg,backgroundColor:colors.white},field:{marginBottom:13},label:{fontSize:11,fontWeight:'800',color:colors.ink,marginBottom:6},input:{height:50,borderWidth:1,borderColor:colors.line,borderRadius:radii.md,paddingHorizontal:13,color:colors.ink,backgroundColor:colors.paper},note:{padding:12,borderRadius:radii.md,backgroundColor:colors.companySoft},noteText:{fontSize:10.5,lineHeight:16,color:colors.companyDark},button:{height:54,borderRadius:radii.md,backgroundColor:colors.companyDark,alignItems:'center',justifyContent:'center',marginTop:16},buttonText:{fontSize:14,fontWeight:'900',color:colors.white},error:{marginTop:15,padding:12,borderRadius:radii.md,backgroundColor:'#FDECEC'},errorText:{fontSize:12,color:'#A33A3A'}});