import { useState } from 'react';
import { Alert, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { router } from 'expo-router';
import { colors } from '../lib/theme';
import { supabase } from '../lib/supabase';

const C=colors;
const skills=['ICU / Critical Care','Mechanical ventilation','Central line management','ECMO','Air ambulance transport','International transport'];
const skillMap:Record<string,string>={'ICU / Critical Care':'icu','Mechanical ventilation':'mechanical-ventilation','Central line management':'central-line','ECMO':'ecmo','Air ambulance transport':'air-ambulance','International transport':'international-transport'};
const languages=['French','English','Spanish','German']; const langCode:Record<string,string>={French:'fr',English:'en',Spanish:'es',German:'de'};
export default function CompanyMission(){
 const [selected,setSelected]=useState(['ICU / Critical Care','Mechanical ventilation']); const [langs,setLangs]=useState(['French']); const [role,setRole]=useState<'doctor'|'nurse'>('nurse'); const [saving,setSaving]=useState(false); const [missionId,setMissionId]=useState('');
 const toggle=(v:string,setter:React.Dispatch<React.SetStateAction<string[]>>)=>setter(a=>a.includes(v)?a.filter(x=>x!==v):[...a,v]);
 async function publish(){
  if(!supabase)return Alert.alert('Supabase not configured','Add the Supabase environment variables before publishing.');
  const {data:{user}}=await supabase.auth.getUser(); if(!user)return Alert.alert('Sign in required','Please sign in before publishing a mission.'); setSaving(true);
  const company=await supabase.from('companies').select('id,verification_status').eq('id',user.id).maybeSingle();
  if(company.error||!company.data){setSaving(false);return Alert.alert('Company setup required','Complete company onboarding before creating a mission.');}
  if(company.data.verification_status!=='verified'){setSaving(false);return Alert.alert('Verification required','Your company must be verified by MediCrew before publishing missions.');}
  const mission=await supabase.from('missions').insert({company_id:user.id,title:`${role==='nurse'?'Nurse':'Doctor'} · Paris → Barcelona`,departure_location:'Paris',destination_location:'Barcelona',departure_at:new Date('2026-08-25T10:30:00+02:00').toISOString(),estimated_duration_hours:8,transport_type:'commercial_flight',professional_type:role,compensation_cents:48000,expenses_covered:true,return_arrangements:'Provided',status:'draft'}).select('id').single();
  if(mission.error||!mission.data){setSaving(false);return Alert.alert('Could not create mission',mission.error?.message||'Unknown error');}
  const ids=await supabase.from('skills').select('id,slug').in('slug',selected.map(x=>skillMap[x]));
  if(ids.error){setSaving(false);await supabase.from('missions').delete().eq('id',mission.data.id);return Alert.alert('Could not load requirements',ids.error.message);}
  const skillRows=(ids.data||[]).map(x=>({mission_id:mission.data.id,skill_id:x.id,kind:'mandatory',minimum_level:'advanced'}));
  const languageRows=langs.map(x=>({mission_id:mission.data.id,language_code:langCode[x],kind:'mandatory',minimum_level:'intermediate'}));
  const req=await supabase.from('mission_requirements').insert([...skillRows,...languageRows]);
  if(req.error){setSaving(false);await supabase.from('missions').delete().eq('id',mission.data.id);return Alert.alert('Could not save requirements',req.error.message);}
  const published=await supabase.rpc('publish_mission',{p_mission_id:mission.data.id}); setSaving(false);
  if(published.error){await supabase.from('missions').delete().eq('id',mission.data.id);return Alert.alert('Could not publish mission',published.error.message);}
  setMissionId(mission.data.id);
 }
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.container}><TouchableOpacity onPress={()=>router.back()}><Text style={s.back}>‹ Back</Text></TouchableOpacity><Text style={s.eyebrow}>NEW MISSION</Text><Text style={s.title}>Build your mission.</Text><Text style={s.subtitle}>MediCrew matches verified professionals against operational requirements only. Do not enter patient information.</Text>
 {missionId?<View style={s.success}><Text style={s.successIcon}>✓</Text><Text style={s.successTitle}>Mission published</Text><Text style={s.successText}>Matching is complete. You can review eligible professionals now.</Text><TouchableOpacity style={s.primary} onPress={()=>router.push({pathname:'/company-candidates',params:{missionId}})}><Text style={s.primaryText}>View matches</Text><Text style={s.primaryArrow}>→</Text></TouchableOpacity><TouchableOpacity style={s.secondary} onPress={()=>router.replace('/company')}><Text style={s.secondaryText}>Back to dashboard</Text></TouchableOpacity></View>:<>
 <Section title="Route"><View style={s.two}><Field label="Departure" value="Paris"/><Field label="Destination" value="Barcelona"/></View></Section><Section title="Schedule"><View style={s.two}><Field label="Date" value="25 August 2026"/><Field label="Departure" value="10:30"/></View><Field label="Estimated duration" value="8 hours"/></Section>
 <Section title="Professional required"><View style={s.segment}>{(['doctor','nurse'] as const).map(x=><TouchableOpacity key={x} style={[s.segmentItem,role===x&&s.segmentActive]} onPress={()=>setRole(x)}><Text style={[s.segmentText,role===x&&s.segmentTextActive]}>{x==='doctor'?'Doctor':'Nurse'}</Text></TouchableOpacity>)}</View></Section>
 <Section title="Requirements"><Text style={s.hint}>V1 uses mandatory clinical requirements. Preferred requirements and per-skill levels will be expanded in the next refinement.</Text>{skills.map(x=><Check key={x} label={x} checked={selected.includes(x)} onPress={()=>toggle(x,setSelected)}/>)}</Section>
 <Section title="Languages">{languages.map(x=><Check key={x} label={x} checked={langs.includes(x)} onPress={()=>toggle(x,setLangs)}/>)}</Section><Section title="Compensation"><View style={s.two}><Field label="Professional fee (€)" value="480"/><Field label="Expenses" value="Covered"/></View></Section>
 <View style={s.notice}><Text style={s.noticeTitle}>Privacy by design</Text><Text style={s.noticeText}>No patient name, diagnosis, medical record or other patient-identifying data is requested by MediCrew.</Text></View><TouchableOpacity disabled={saving} style={[s.primary,saving&&{opacity:.6}]} onPress={publish}><Text style={s.primaryText}>{saving?'Publishing…':'Publish & find matches'}</Text><Text style={s.primaryArrow}>→</Text></TouchableOpacity></>}
 </ScrollView></SafeAreaView>;
}
function Section({title,children}:{title:string;children:React.ReactNode}){return <View style={s.section}><Text style={s.sectionTitle}>{title}</Text>{children}</View>}
function Field({label,value}:{label:string;value:string}){return <View style={s.field}><Text style={s.label}>{label}</Text><TextInput value={value} editable={false} style={s.input}/></View>}
function Check({label,checked,onPress}:{label:string;checked:boolean;onPress:()=>void}){return <TouchableOpacity style={s.check} onPress={onPress}><View style={[s.box,checked&&s.boxChecked]}>{checked&&<Text style={s.tick}>✓</Text>}</View><Text style={s.checkText}>{label}</Text></TouchableOpacity>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:C.paper},container:{padding:22,paddingBottom:50},back:{color:C.ink,fontWeight:'700',fontSize:14,marginBottom:24},eyebrow:{color:C.green,fontWeight:'800',fontSize:11,letterSpacing:1.5},title:{color:C.ink,fontWeight:'800',fontSize:30,letterSpacing:-.8,marginTop:7},subtitle:{color:C.muted,fontSize:13,lineHeight:19,marginTop:7,marginBottom:25},section:{backgroundColor:C.white,borderWidth:1,borderColor:C.line,borderRadius:18,padding:17,marginBottom:13},sectionTitle:{fontSize:17,fontWeight:'800',color:C.ink,marginBottom:14},hint:{fontSize:12,color:C.muted,lineHeight:18,marginBottom:10},two:{flexDirection:'row',gap:10},field:{flex:1,marginBottom:10},label:{fontSize:11,color:C.muted,fontWeight:'700',marginBottom:6},input:{borderWidth:1,borderColor:C.line,borderRadius:11,paddingHorizontal:12,height:45,color:C.ink,fontSize:14,backgroundColor:'#FAFBFA'},segment:{flexDirection:'row',backgroundColor:'#EEF1EF',padding:4,borderRadius:12},segmentItem:{flex:1,paddingVertical:11,alignItems:'center',borderRadius:9},segmentActive:{backgroundColor:C.white},segmentText:{color:C.muted,fontWeight:'700'},segmentTextActive:{color:C.ink},check:{flexDirection:'row',alignItems:'center',paddingVertical:10},box:{width:22,height:22,borderRadius:6,borderWidth:1.5,borderColor:'#C8CFCA',alignItems:'center',justifyContent:'center',marginRight:11},boxChecked:{backgroundColor:C.green,borderColor:C.green},tick:{color:C.white,fontWeight:'900',fontSize:13},checkText:{flex:1,color:C.ink,fontSize:13,fontWeight:'600'},notice:{backgroundColor:C.greenSoft,borderRadius:16,padding:16,marginBottom:15},noticeTitle:{color:'#117A5B',fontWeight:'800',fontSize:13},noticeText:{color:'#3C6659',fontSize:12,lineHeight:18,marginTop:5},primary:{backgroundColor:C.ink,borderRadius:16,minHeight:56,paddingHorizontal:18,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:12},primaryText:{color:C.white,fontSize:15,fontWeight:'800'},primaryArrow:{color:C.green,fontSize:22},secondary:{minHeight:48,alignItems:'center',justifyContent:'center'},secondaryText:{color:C.muted,fontWeight:'700'},success:{backgroundColor:C.white,borderWidth:1,borderColor:C.line,borderRadius:20,padding:24,alignItems:'center',marginTop:25},successIcon:{width:54,height:54,borderRadius:27,backgroundColor:C.greenSoft,color:'#117A5B',textAlign:'center',textAlignVertical:'center',fontSize:28,fontWeight:'800'},successTitle:{fontSize:22,fontWeight:'800',color:C.ink,marginTop:15},successText:{color:C.muted,textAlign:'center',lineHeight:19,marginTop:7,marginBottom:20}});
