import { router } from 'expo-router';
import { SafeAreaView, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { useState } from 'react';

const C = { bg:'#F7F8F6', ink:'#101214', muted:'#6F7672', green:'#18B889', soft:'#DDF5ED', white:'#FFF', line:'#E5E8E5', red:'#D94A4A' };
const skills = ['ICU / Critical care','Mechanical ventilation','Central line','ECMO','Air ambulance','International transport'];
const languages = ['French','English','Spanish','German'];

export default function CompanyMission() {
 const [selectedSkills,setSelectedSkills]=useState<string[]>(['ICU / Critical care','Mechanical ventilation']);
 const [selectedLanguages,setSelectedLanguages]=useState<string[]>(['French']);
 const [role,setRole]=useState<'Doctor'|'Nurse'>('Nurse');
 const [published,setPublished]=useState(false);
 const toggle=(v:string,setter:React.Dispatch<React.SetStateAction<string[]>>) => setter(a=>a.includes(v)?a.filter(x=>x!==v):[...a,v]);
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.container}>
  <TouchableOpacity onPress={()=>router.back()}><Text style={s.back}>‹  Back</Text></TouchableOpacity>
  <Text style={s.eyebrow}>NEW MISSION</Text><Text style={s.title}>Build your mission.</Text><Text style={s.subtitle}>Only include operational requirements. Patient information does not belong in the MediCrew mission listing.</Text>
  {published ? <View style={s.success}><Text style={s.successIcon}>✓</Text><Text style={s.successTitle}>Mission published</Text><Text style={s.successText}>MediCrew is now matching verified professionals against your requirements.</Text><TouchableOpacity style={s.primary} onPress={()=>router.push('/company')}><Text style={s.primaryText}>Back to dashboard</Text></TouchableOpacity></View> : <>
  <Section title="Route"><View style={s.two}><Field label="Departure" value="Paris"/><Field label="Destination" value="Barcelona"/></View></Section>
  <Section title="Schedule"><View style={s.two}><Field label="Date" value="25 August"/><Field label="Departure" value="10:30"/></View><Field label="Estimated duration" value="8 hours"/></Section>
  <Section title="Professional required"><View style={s.segment}>{(['Doctor','Nurse'] as const).map(x=><TouchableOpacity key={x} style={[s.segmentItem,role===x&&s.segmentActive]} onPress={()=>setRole(x)}><Text style={[s.segmentText,role===x&&s.segmentTextActive]}>{x}</Text></TouchableOpacity>)}</View></Section>
  <Section title="Clinical & transport requirements"><Text style={s.hint}>Mandatory requirements are hard eligibility filters. Preferred requirements improve ranking.</Text><Text style={s.smallTitle}>Select requirements</Text>{skills.map(x=><Check key={x} label={x} checked={selectedSkills.includes(x)} onPress={()=>toggle(x,setSelectedSkills)}/>)}</Section>
  <Section title="Languages"><Text style={s.hint}>Select every language the professional must be able to use professionally.</Text>{languages.map(x=><Check key={x} label={x} checked={selectedLanguages.includes(x)} onPress={()=>toggle(x,setSelectedLanguages)}/>)}</Section>
  <Section title="Compensation"><View style={s.two}><Field label="Professional fee" value="480"/><Field label="Currency" value="EUR"/></View><Text style={s.hint}>Flights, hotel, taxi and other agreed expenses can be marked as covered in the final workflow.</Text></Section>
  <View style={s.notice}><Text style={s.noticeTitle}>Privacy by design</Text><Text style={s.noticeText}>Do not enter patient names, diagnoses, medical records or other patient-identifying information here.</Text></View>
  <TouchableOpacity style={s.primary} onPress={()=>setPublished(true)}><Text style={s.primaryText}>Publish & find matches</Text><Text style={s.primaryArrow}>→</Text></TouchableOpacity>
  </>}
 </ScrollView></SafeAreaView>
}
function Section({title,children}:{title:string;children:React.ReactNode}){return <View style={s.section}><Text style={s.sectionTitle}>{title}</Text>{children}</View>}
function Field({label,value}:{label:string;value:string}){return <View style={s.field}><Text style={s.label}>{label}</Text><TextInput value={value} onChangeText={()=>{}} style={s.input} placeholderTextColor={C.muted}/></View>}
function Check({label,checked,onPress}:{label:string;checked:boolean;onPress:()=>void}){return <TouchableOpacity style={s.check} onPress={onPress}><View style={[s.box,checked&&s.boxChecked]}>{checked&&<Text style={s.tick}>✓</Text>}</View><Text style={s.checkText}>{label}</Text><Text style={s.required}>{['ICU / Critical care','Mechanical ventilation'].includes(label)?'Required':'Preferred'}</Text></TouchableOpacity>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:C.bg},container:{padding:22,paddingBottom:50},back:{color:C.ink,fontWeight:'700',fontSize:14,marginBottom:24},eyebrow:{color:C.green,fontWeight:'800',fontSize:11,letterSpacing:1.5},title:{color:C.ink,fontWeight:'800',fontSize:30,letterSpacing:-.8,marginTop:7},subtitle:{color:C.muted,fontSize:13,lineHeight:19,marginTop:7,marginBottom:25},section:{backgroundColor:C.white,borderWidth:1,borderColor:C.line,borderRadius:18,padding:17,marginBottom:13},sectionTitle:{fontSize:17,fontWeight:'800',color:C.ink,marginBottom:14},two:{flexDirection:'row',gap:10},field:{flex:1,marginBottom:10},label:{fontSize:11,color:C.muted,fontWeight:'700',marginBottom:6},input:{borderWidth:1,borderColor:C.line,borderRadius:11,paddingHorizontal:12,height:45,color:C.ink,fontSize:14},segment:{flexDirection:'row',backgroundColor:'#EEF1EF',padding:4,borderRadius:12},segmentItem:{flex:1,paddingVertical:11,alignItems:'center',borderRadius:9},segmentActive:{backgroundColor:C.white},segmentText:{color:C.muted,fontWeight:'700'},segmentTextActive:{color:C.ink},hint:{fontSize:12,color:C.muted,lineHeight:18,marginBottom:13},smallTitle:{fontSize:11,color:C.ink,fontWeight:'800',marginBottom:7,textTransform:'uppercase',letterSpacing:.8},check:{flexDirection:'row',alignItems:'center',paddingVertical:10},box:{width:22,height:22,borderRadius:6,borderWidth:1.5,borderColor:'#C8CFCA',alignItems:'center',justifyContent:'center',marginRight:11},boxChecked:{backgroundColor:C.green,borderColor:C.green},tick:{color:C.white,fontWeight:'900',fontSize:13},checkText:{flex:1,color:C.ink,fontSize:13,fontWeight:'600'},required:{fontSize:9,color:C.muted,fontWeight:'700',textTransform:'uppercase'},notice:{backgroundColor:C.soft,borderRadius:16,padding:16,marginBottom:15},noticeTitle:{color:'#117A5B',fontWeight:'800',fontSize:13},noticeText:{color:'#3C6659',fontSize:12,lineHeight:18,marginTop:5},primary:{backgroundColor:C.ink,borderRadius:16,minHeight:56,paddingHorizontal:18,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:12},primaryText:{color:C.white,fontSize:15,fontWeight:'800'},primaryArrow:{color:C.green,fontSize:22},success:{backgroundColor:C.white,borderWidth:1,borderColor:C.line,borderRadius:20,padding:24,alignItems:'center',marginTop:25},successIcon:{width:54,height:54,borderRadius:27,backgroundColor:C.soft,color:'#117A5B',textAlign:'center',textAlignVertical:'center',fontSize:28,fontWeight:'800'},successTitle:{fontSize:22,fontWeight:'800',color:C.ink,marginTop:15},successText:{color:C.muted,textAlign:'center',lineHeight:19,marginTop:7,marginBottom:20}});
