import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { colors, radii } from '../lib/theme';

const missions = [
  { from:'Paris', to:'Barcelona', date:'25 AUG', time:'10:30', type:'COMMERCIAL FLIGHT', role:'ICU NURSE', pay:'€480', match:'97%' },
  { from:'Lyon', to:'Geneva', date:'28 AUG', time:'08:15', type:'ROAD TRANSPORT', role:'DOCTOR', pay:'€620', match:'94%' },
];

export default function Home(){
 return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.container}>
   <View style={styles.header}><View><Text style={styles.eyebrow}>MEDICREW</Text><Text style={styles.greeting}>Good evening.</Text></View><Pressable style={styles.avatar}><Text style={styles.avatarText}>D</Text></Pressable></View>
   <View style={styles.status}><View><Text style={styles.statusLabel}>AVAILABILITY</Text><Text style={styles.statusTitle}>Available now</Text><Text style={styles.statusText}>Montpellier · 200 km radius</Text></View><View style={styles.dot}/></View>
   <View style={styles.sectionHeader}><Text style={styles.sectionTitle}>Recommended missions</Text><Text style={styles.see}>See all</Text></View>
   {missions.map((m)=><Pressable key={m.from+m.to} style={styles.card} onPress={()=>router.push('/mission')}><View style={styles.top}><Text style={styles.date}>{m.date}</Text><Text style={styles.match}>{m.match} MATCH</Text></View><Text style={styles.route}>{m.from} <Text style={styles.arrow}>→</Text> {m.to}</Text><Text style={styles.meta}>{m.time} · {m.type}</Text><View style={styles.divider}/><View style={styles.bottom}><View><Text style={styles.role}>{m.role}</Text><Text style={styles.expense}>Expenses covered</Text></View><Text style={styles.pay}>{m.pay}</Text></View></Pressable>)}
   <View style={styles.nav}><Nav label="Home" active/><Nav label="Missions"/><Nav label="Calendar"/><Nav label="Profile"/></View>
 </ScrollView></SafeAreaView>
}
function Nav({label,active=false}:{label:string;active?:boolean}){return <Pressable style={styles.navItem}><View style={[styles.navDot,active&&styles.navActive]}/><Text style={[styles.navText,active&&styles.navTextActive]}>{label}</Text></Pressable>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.paper},container:{padding:24,paddingBottom:35},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},eyebrow:{fontSize:11,fontWeight:'800',letterSpacing:1.5,color:colors.green},greeting:{fontSize:30,fontWeight:'800',color:colors.ink,letterSpacing:-.8,marginTop:4},avatar:{width:44,height:44,borderRadius:22,backgroundColor:colors.ink,alignItems:'center',justifyContent:'center'},avatarText:{color:colors.white,fontWeight:'800'},status:{marginTop:24,padding:18,borderRadius:radii.lg,backgroundColor:colors.ink,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},statusLabel:{fontSize:10,fontWeight:'800',letterSpacing:1.2,color:colors.green},statusTitle:{fontSize:21,fontWeight:'800',color:colors.white,marginTop:4},statusText:{fontSize:13,color:'#B8BFBC',marginTop:3},dot:{width:13,height:13,borderRadius:7,backgroundColor:colors.green},sectionHeader:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginTop:30,marginBottom:12},sectionTitle:{fontSize:19,fontWeight:'800',color:colors.ink},see:{fontSize:13,fontWeight:'700',color:colors.green},card:{backgroundColor:colors.white,borderWidth:1,borderColor:colors.line,borderRadius:radii.lg,padding:18,marginBottom:12},top:{flexDirection:'row',justifyContent:'space-between'},date:{fontSize:11,fontWeight:'800',color:colors.muted,letterSpacing:1},match:{fontSize:10,fontWeight:'800',color:colors.green,letterSpacing:.7},route:{fontSize:26,fontWeight:'800',color:colors.ink,letterSpacing:-.7,marginTop:12},arrow:{color:colors.green},meta:{fontSize:13,color:colors.muted,marginTop:5},divider:{height:1,backgroundColor:colors.line,marginVertical:16},bottom:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},role:{fontSize:13,fontWeight:'800',color:colors.ink},expense:{fontSize:12,color:colors.muted,marginTop:3},pay:{fontSize:20,fontWeight:'800',color:colors.ink},nav:{flexDirection:'row',justifyContent:'space-around',backgroundColor:colors.white,borderWidth:1,borderColor:colors.line,borderRadius:radii.lg,paddingVertical:12,marginTop:18},navItem:{alignItems:'center',gap:5},navDot:{width:5,height:5,borderRadius:3,backgroundColor:'#C9CECC'},navActive:{backgroundColor:colors.green},navText:{fontSize:11,color:colors.muted,fontWeight:'600'},navTextActive:{color:colors.ink,fontWeight:'800'}});
