import { LinearGradient } from 'expo-linear-gradient';
import { useEffect, useRef, useState } from 'react';
import { Animated, Pressable, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import Svg, { Circle, Path, Rect } from 'react-native-svg';
import { colors, gradients, radii, shadows } from '../lib/theme';
import { MediCrewLogo } from '../lib/brand';

type Role='professional'|'company';
export default function Welcome(){
 const[role,setRole]=useState<Role|null>(null);const enter=useRef(new Animated.Value(0)).current;
 useEffect(()=>{Animated.spring(enter,{toValue:1,useNativeDriver:true,friction:8,tension:55}).start()},[enter]);
 const palette=role==='company'?gradients.company:gradients.professional;
 return <SafeAreaView style={styles.safe}><LinearGradient colors={gradients.soft} start={{x:0,y:0}} end={{x:1,y:1}} style={styles.gradient}><Animated.View style={[styles.container,{opacity:enter,transform:[{translateY:enter.interpolate({inputRange:[0,1],outputRange:[14,0]})}]}]}><View><MediCrewLogo/><View style={styles.badge}><View style={styles.dot}/><Text style={styles.badgeText}>VERIFIED MEDICAL MISSION NETWORK</Text></View><View style={styles.hero}><Text style={styles.eyebrow}>CARE MOVES FORWARD</Text><Text style={styles.title}>One network. Two sides of every mission.</Text><Text style={styles.subtitle}>Verified doctors and nurses meet transport, repatriation and event organizations that need them.</Text></View></View><View><View style={styles.card}><Text style={styles.cardTitle}>Choose your side</Text><RoleCard role="professional" selected={role==='professional'} onPress={()=>setRole('professional')}/><RoleCard role="company" selected={role==='company'} onPress={()=>setRole('company')}/></View><Pressable disabled={!role} onPress={()=>role&&router.push({pathname:'/auth',params:{role}})}><LinearGradient colors={palette} start={{x:0,y:.5}} end={{x:1,y:.5}} style={[styles.button,!role&&styles.buttonDisabled]}><Text style={styles.buttonText}>{role==='company'?'Continue as company':role==='professional'?'Continue as professional':'Choose a side'}</Text><Text style={styles.buttonArrow}>→</Text></LinearGradient></Pressable><Pressable onPress={()=>router.push('/legal')} style={styles.legal}><Text style={styles.legalText}>Privacy · Terms · Data policy</Text></Pressable><Text style={styles.footer}>MediCrew · Verified people. Safer missions.</Text></View></Animated.View></LinearGradient></SafeAreaView>}

function RoleCard({role,selected,onPress}:{role:Role;selected:boolean;onPress:()=>void}){const company=role==='company';return <Pressable onPress={onPress} style={[styles.choice,company?styles.companyChoice:styles.proChoice,selected&&(company?styles.companyActive:styles.proActive)]}><View style={[styles.illustrationWrap,{backgroundColor:company?colors.companySoft:colors.proSoft}]}>{company?<CompanyIllustration/>:<ProIllustration/>}</View><View style={styles.choiceBody}><Text style={[styles.roleTag,{color:company?colors.companyDark:colors.proDark}]}>{company?'ORGANIZATION':'MEDICAL PROFESSIONAL'}</Text><Text style={styles.choiceTitle}>{company?'Company / event organization':'Doctor or nurse'}</Text><Text style={styles.choiceText}>{company?'Transport, repatriation, event medical staffing':'Verified missions matched to your credentials'}</Text></View><Text style={[styles.chevron,{color:company?colors.company:colors.pro}]}>›</Text></Pressable>}
function ProIllustration(){return <Svg width={58} height={58} viewBox="0 0 64 64"><Circle cx="32" cy="21" r="10" fill={colors.pro}/><Path d="M15 54c2-13 9-20 17-20s15 7 17 20" fill="none" stroke={colors.proDark} strokeWidth="6" strokeLinecap="round"/><Path d="M25 39c1 7 3 11 7 11s6-4 7-11" fill="none" stroke={colors.white} strokeWidth="3"/><Circle cx="48" cy="18" r="7" fill={colors.white}/><Path d="M48 14v8M44 18h8" stroke={colors.proDark} strokeWidth="2.5" strokeLinecap="round"/></Svg>}
function CompanyIllustration(){return <Svg width={58} height={58} viewBox="0 0 64 64"><Rect x="10" y="21" width="44" height="33" rx="8" fill={colors.company}/><Path d="M20 21v-7h24v7" stroke={colors.companyDark} strokeWidth="5" strokeLinecap="round"/><Rect x="18" y="30" width="10" height="8" rx="2" fill={colors.white}/><Rect x="36" y="30" width="10" height="8" rx="2" fill={colors.white}/><Path d="M32 43v11" stroke={colors.companyDark} strokeWidth="4"/><Circle cx="51" cy="17" r="8" fill={colors.white}/><Path d="M51 13v8M47 17h8" stroke={colors.companyDark} strokeWidth="2.5" strokeLinecap="round"/></Svg>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.paper},gradient:{flex:1},container:{flex:1,padding:22,paddingTop:10,justifyContent:'space-between'},badge:{alignSelf:'flex-start',flexDirection:'row',alignItems:'center',gap:7,borderWidth:1,borderColor:'#CBEBDD',backgroundColor:'#F5FFF8',borderRadius:radii.pill,paddingHorizontal:10,paddingVertical:7,marginTop:4},dot:{width:7,height:7,borderRadius:4,backgroundColor:colors.green},badgeText:{fontSize:8,fontWeight:'900',letterSpacing:.7,color:colors.greenDark},hero:{marginTop:18},eyebrow:{color:colors.greenDark,fontWeight:'900',letterSpacing:1.5,fontSize:11,marginBottom:9},title:{fontSize:35,lineHeight:39,fontWeight:'900',color:colors.ink,letterSpacing:-1.45},subtitle:{marginTop:12,color:colors.muted,fontSize:14,lineHeight:21},card:{backgroundColor:colors.white,borderRadius:radii.lg,padding:15,borderWidth:1,borderColor:colors.line,...shadows.card},cardTitle:{fontSize:15,fontWeight:'900',color:colors.ink,marginBottom:3},choice:{padding:12,borderRadius:20,borderWidth:1.5,marginTop:10,flexDirection:'row',alignItems:'center',gap:11},proChoice:{borderColor:'#CFE9DF',backgroundColor:'#FBFEFC'},companyChoice:{borderColor:'#D4E6E2',backgroundColor:'#FBFDFC'},proActive:{borderColor:colors.pro,backgroundColor:colors.proSoft},companyActive:{borderColor:colors.company,backgroundColor:colors.companySoft},illustrationWrap:{width:64,height:64,borderRadius:20,alignItems:'center',justifyContent:'center'},choiceBody:{flex:1},roleTag:{fontSize:8,fontWeight:'900',letterSpacing:.9},choiceTitle:{fontSize:14,fontWeight:'900',color:colors.ink,marginTop:3},choiceText:{fontSize:10.5,lineHeight:15,color:colors.muted,marginTop:3},chevron:{fontSize:28,fontWeight:'700'},button:{height:58,borderRadius:radii.md,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:12,overflow:'hidden',marginTop:12},buttonDisabled:{opacity:.35},buttonText:{color:colors.white,fontSize:16,fontWeight:'900'},buttonArrow:{color:colors.white,fontSize:22,fontWeight:'900'},legal:{alignItems:'center',paddingTop:10},legalText:{fontSize:10,color:colors.greenDark,fontWeight:'800'},footer:{textAlign:'center',color:colors.muted,fontSize:11,marginTop:6}});