import { LinearGradient } from 'expo-linear-gradient';
import { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { colors, gradients, radii } from '../lib/theme';
import { MediCrewLogo } from '../lib/brand';

export default function Welcome(){const[role,setRole]=useState<'professional'|'company'|null>(null);return <SafeAreaView style={styles.safe}><LinearGradient colors={gradients.soft} start={{x:0,y:0}} end={{x:1,y:1}} style={styles.gradient}><View style={styles.container}><View><MediCrewLogo/><View style={styles.badge}><View style={styles.dot}/><Text style={styles.badgeText}>VERIFIED MEDICAL TRANSPORT NETWORK</Text></View><View style={styles.hero}><Text style={styles.eyebrow}>CARE MOVES FORWARD</Text><Text style={styles.title}>The right medical professional. When the mission needs them.</Text><Text style={styles.subtitle}>A verified network connecting medical transport companies with qualified doctors and nurses.</Text></View></View><View><View style={styles.card}><Text style={styles.cardTitle}>How will you use MediCrew?</Text><Pressable style={[styles.choice,role==='professional'&&styles.choiceActive]} onPress={()=>setRole('professional')}><View style={styles.iconCircle}><Text style={styles.icon}>+</Text></View><View style={styles.choiceBody}><Text style={styles.choiceTitle}>I'm a medical professional</Text><Text style={styles.choiceText}>Find and accept transport missions</Text></View><Text style={styles.chevron}>›</Text></Pressable><Pressable style={[styles.choice,role==='company'&&styles.choiceActive]} onPress={()=>setRole('company')}><View style={styles.iconCircle}><Text style={styles.icon}>M</Text></View><View style={styles.choiceBody}><Text style={styles.choiceTitle}>I'm a company</Text><Text style={styles.choiceText}>Find qualified professionals for missions</Text></View><Text style={styles.chevron}>›</Text></Pressable></View><Pressable disabled={!role} onPress={()=>role&&router.push({pathname:'/auth',params:{role}})}><LinearGradient colors={gradients.primary} start={{x:0,y:.5}} end={{x:1,y:.5}} style={[styles.button,!role&&styles.buttonDisabled]}><Text style={styles.buttonText}>Create an account</Text><Text style={styles.buttonArrow}>→</Text></LinearGradient></Pressable><Text style={styles.footer}>MediCrew · Verified people. Safer missions.</Text></View></View></LinearGradient></SafeAreaView>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.paper},gradient:{flex:1},container:{flex:1,padding:22,paddingTop:10,justifyContent:'space-between'},badge:{alignSelf:'flex-start',flexDirection:'row',alignItems:'center',gap:7,borderWidth:1,borderColor:'#CBEBDD',backgroundColor:'#F5FFF8',borderRadius:radii.pill,paddingHorizontal:10,paddingVertical:7,marginTop:4},dot:{width:7,height:7,borderRadius:4,backgroundColor:colors.green},badgeText:{fontSize:8,fontWeight:'900',letterSpacing:.7,color:colors.greenDark},hero:{marginTop:20},eyebrow:{color:colors.greenDark,fontWeight:'900',letterSpacing:1.5,fontSize:11,marginBottom:10},title:{fontSize:36,lineHeight:40,fontWeight:'900',color:colors.ink,letterSpacing:-1.5},subtitle:{marginTop:13,color:colors.muted,fontSize:15,lineHeight:22},card:{backgroundColor:colors.white,borderRadius:radii.lg,padding:16,borderWidth:1,borderColor:colors.line,shadowColor:colors.ink,shadowOpacity:.05,shadowRadius:12,shadowOffset:{width:0,height:5},elevation:2},cardTitle:{fontSize:15,fontWeight:'800',color:colors.ink,marginBottom:4},choice:{padding:13,borderRadius:radii.md,borderWidth:1,borderColor:colors.line,marginTop:9,flexDirection:'row',alignItems:'center',gap:10},choiceActive:{borderColor:colors.green,backgroundColor:colors.greenSoft},iconCircle:{width:35,height:35,borderRadius:18,backgroundColor:colors.greenSoft,alignItems:'center',justifyContent:'center'},icon:{fontSize:16,fontWeight:'900',color:colors.greenDark},choiceBody:{flex:1},choiceTitle:{fontSize:14,fontWeight:'800',color:colors.ink},choiceText:{fontSize:11,color:colors.muted,marginTop:3},chevron:{fontSize:25,color:colors.muted},button:{height:56,borderRadius:radii.md,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:12,overflow:'hidden',marginTop:12},buttonDisabled:{opacity:.35},buttonText:{color:colors.white,fontSize:16,fontWeight:'900'},buttonArrow:{color:'#EFFFF8',fontSize:22,fontWeight:'900'},footer:{textAlign:'center',color:colors.muted,fontSize:11,marginTop:10}});