import { useEffect, useState } from 'react';
import { ActivityIndicator, Image, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { supabase } from '../lib/supabase';
import { avatarUrl } from '../lib/avatar';
import { colors, radii } from '../lib/theme';

type Conversation={conversation_id:string;other_profile_id:string;display_name:string;avatar_url:string|null;role:'professional'|'company';last_message:string|null;last_message_at:string|null};
export default function Messages(){const[items,setItems]=useState<Conversation[]>([]);const[loading,setLoading]=useState(true);const[preview,setPreview]=useState(false);const[error,setError]=useState('');useEffect(()=>{load()},[]);async function load(){if(!supabase){setLoading(false);return}const{data:{user}}=await supabase.auth.getUser();if(!user){if(__DEV__)setPreview(true);setLoading(false);return}const{data,error:e}=await supabase.rpc('my_direct_conversations');if(e)setError(e.message);else setItems((data||[]) as Conversation[]);setLoading(false)}return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.container}><Pressable onPress={()=>router.back()}><Text style={s.back}>‹ Back</Text></Pressable><View style={s.header}><View><Text style={s.eyebrow}>MESSAGES</Text><Text style={s.title}>Conversations.</Text></View><Pressable onPress={()=>router.push('/network')} style={s.new}><Text style={s.newText}>New</Text></Pressable></View><Text style={s.sub}>Direct messaging works professional ↔ professional and professional ↔ organization. Use mission chats for mission-specific operational coordination.</Text>{preview?<View style={s.info}><Text style={s.infoText}>Development account: no fake conversations are shown.</Text></View>:null}{loading?<ActivityIndicator size="large" color={colors.green}/>:error?<View style={s.error}><Text style={s.errorText}>{error}</Text></View>:items.length===0?<View style={s.empty}><Text style={s.emptyTitle}>No conversations yet</Text><Text style={s.emptyText}>Open a verified profile from the Network and tap Message.</Text></View>:items.map(x=>{const img=avatarUrl(x.avatar_url);return <Pressable key={x.conversation_id} style={s.row} onPress={()=>router.push({pathname:'/direct-chat',params:{conversationId:x.conversation_id,title:x.display_name}})}>{img?<Image source={{uri:img}} style={s.avatar}/>:<View style={[s.avatar,s.fallback]}><Text style={s.initial}>{x.display_name.slice(0,2).toUpperCase()}</Text></View>}<View style={{flex:1}}><View style={s.top}><Text style={s.name}>{x.display_name}</Text>{x.last_message_at?<Text style={s.time}>{new Date(x.last_message_at).toLocaleDateString()}</Text>:null}</View><Text numberOfLines={1} style={s.last}>{x.last_message||'Start the conversation'}</Text><Text style={s.role}>{x.role==='company'?'Organization':'Professional'}</Text></View><Text style={s.arrow}>›</Text></Pressable>})}</ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.paper},container:{padding:22,paddingBottom:45},back:{fontSize:15,fontWeight:'800',color:colors.ink,marginBottom:22},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:1.4,color:colors.green},title:{fontSize:34,fontWeight:'900',color:colors.ink,marginTop:5},new:{paddingHorizontal:14,paddingVertical:9,borderRadius:99,backgroundColor:colors.ink},newText:{fontSize:11,fontWeight:'900',color:colors.white},sub:{fontSize:12.5,lineHeight:19,color:colors.muted,marginTop:8,marginBottom:18},row:{paddingVertical:12,borderBottomWidth:1,borderBottomColor:colors.line,flexDirection:'row',gap:12,alignItems:'center'},avatar:{width:50,height:50,borderRadius:17},fallback:{backgroundColor:colors.greenSoft,alignItems:'center',justifyContent:'center'},initial:{fontSize:12,fontWeight:'900',color:colors.greenDark},top:{flexDirection:'row',justifyContent:'space-between',gap:8},name:{fontSize:14,fontWeight:'900',color:colors.ink,flex:1},time:{fontSize:9.5,color:colors.muted},last:{fontSize:11.5,color:colors.muted,marginTop:4},role:{fontSize:9,fontWeight:'800',color:colors.greenDark,marginTop:4},arrow:{fontSize:23,color:colors.muted},empty:{padding:22,borderWidth:1,borderColor:colors.line,borderRadius:radii.lg,backgroundColor:colors.white},emptyTitle:{fontSize:16,fontWeight:'900',color:colors.ink},emptyText:{fontSize:12,lineHeight:18,color:colors.muted,marginTop:4},info:{padding:12,borderRadius:radii.md,backgroundColor:colors.greenSoft,marginBottom:12},infoText:{fontSize:11,color:colors.greenDark},error:{padding:12,borderRadius:radii.md,backgroundColor:'#FDECEC'},errorText:{fontSize:12,color:colors.danger}});