import { SafeAreaView, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { colors, radii } from '../lib/theme';

export default function MissionConfirmed(){
 const {missionId}=useLocalSearchParams<{missionId:string}>();
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.container}><View style={s.icon}><Text style={s.tick}>✓</Text></View><Text style={s.eyebrow}>MISSION CONFIRMED</Text><Text style={s.title}>Your crew is confirmed.</Text><Text style={s.sub}>The selected professional has been notified. The mission is now protected from further selection.</Text><View style={s.card}><Row label="Status" value="Confirmed"/><Row label="Mission ID" value={missionId?missionId.slice(0,8).toUpperCase():'—'}/><Row label="Next step" value="Coordinate securely"/></View><TouchableOpacity style={s.primary} onPress={()=>router.push({pathname:'/chat',params:{missionId}})}><Text style={s.primaryText}>Open mission chat</Text><Text style={s.arrow}>→</Text></TouchableOpacity><TouchableOpacity style={s.secondary} onPress={()=>router.replace('/company')}><Text style={s.secondaryText}>Back to dashboard</Text></TouchableOpacity></ScrollView></SafeAreaView>
}
function Row({label,value}:{label:string;value:string}){return <View style={s.row}><Text style={s.label}>{label}</Text><Text style={s.value}>{value}</Text></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.paper},container:{padding:24,paddingTop:60,paddingBottom:40,alignItems:'center'},icon:{width:72,height:72,borderRadius:36,backgroundColor:colors.greenSoft,alignItems:'center',justifyContent:'center',marginBottom:22},tick:{fontSize:34,fontWeight:'900',color:colors.green},eyebrow:{fontSize:11,fontWeight:'900',letterSpacing:1.5,color:colors.green},title:{fontSize:32,lineHeight:37,fontWeight:'800',color:colors.ink,textAlign:'center',letterSpacing:-1,marginTop:8},sub:{fontSize:14,lineHeight:21,color:colors.muted,textAlign:'center',marginTop:10},card:{width:'100%',backgroundColor:colors.white,borderWidth:1,borderColor:colors.line,borderRadius:radii.lg,padding:18,marginTop:25},row:{flexDirection:'row',justifyContent:'space-between',paddingVertical:12,borderBottomWidth:1,borderBottomColor:colors.line},label:{fontSize:12,color:colors.muted},value:{fontSize:13,fontWeight:'800',color:colors.ink},primary:{width:'100%',minHeight:55,borderRadius:radii.md,backgroundColor:colors.ink,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:12,marginTop:18},primaryText:{color:colors.white,fontWeight:'800',fontSize:15},arrow:{color:colors.green,fontSize:21},secondary:{minHeight:48,justifyContent:'center'},secondaryText:{color:colors.muted,fontWeight:'700'}});
