import { Alert,Linking,ScrollView,StyleSheet,Text,TouchableOpacity,View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router,useLocalSearchParams } from 'expo-router';
import { colors,radii } from '../lib/theme';
import { supabase } from '../lib/supabase';
import { usePreferences } from '../lib/preferences-context';
import { localize } from '../lib/i18n';
export default function MissionConfirmed(){const prefs=usePreferences(),L=(en:string,fr:string,es:string)=>localize(prefs.language,en,fr,es);const{missionId}=useLocalSearchParams<{missionId:string}>();
 async function rib(){if(!supabase||!missionId)return;const app=await supabase.from('mission_applications').select('professional_id').eq('mission_id',missionId).eq('status','accepted').maybeSingle();if(app.error||!app.data)return Alert.alert('RIB',app.error?.message||L('No selected professional found.','Aucun professionnel sélectionné.','No se encontró al profesional.'));const doc=await supabase.from('professional_documents').select('storage_path').eq('professional_id',app.data.professional_id).eq('document_type','bank_details').eq('status','verified').order('created_at',{ascending:false}).limit(1).maybeSingle();if(doc.error||!doc.data?.storage_path)return Alert.alert('RIB',doc.error?.message||L('The verified RIB is not available yet.','Le RIB vérifié n’est pas encore disponible.','Los datos bancarios verificados aún no están disponibles.'));const signed=await supabase.storage.from('professional-documents').createSignedUrl(doc.data.storage_path,300);if(signed.error)return Alert.alert('RIB',signed.error.message);if(signed.data?.signedUrl)await Linking.openURL(signed.data.signedUrl)}
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.container}><View style={s.icon}><Text style={s.tick}>✓</Text></View><Text style={s.eyebrow}>{L('MISSION CONFIRMED','MISSION CONFIRMÉE','MISIÓN CONFIRMADA')}</Text><Text style={s.title}>{L('Your crew is confirmed.','Votre équipe est confirmée.','Tu equipo está confirmado.')}</Text><Text style={s.sub}>{L('The organization and professional arrange payment directly. MediCrew provides the secure RIB and chat but never receives or transfers the mission payment.','L’entreprise et le professionnel organisent directement le paiement. MediCrew fournit le RIB sécurisé et le chat, mais ne reçoit ni ne transfère le paiement de la mission.','La empresa y el profesional organizan el pago directamente. MediCrew facilita los datos bancarios y el chat, pero no recibe ni transfiere el pago.')}</Text><View style={s.card}><Row label={L('Status','Statut','Estado')} value={L('Confirmed','Confirmée','Confirmada')}/><Row label={L('Mission ID','ID mission','ID de misión')} value={missionId?missionId.slice(0,8).toUpperCase():'—'}/><Row label={L('Professional payment','Paiement du professionnel','Pago al profesional')} value={L('Direct payment','Paiement direct','Pago directo')}/></View><TouchableOpacity style={s.rib} onPress={rib}><Text style={s.ribText}>{L('Open the professional’s RIB','Ouvrir le RIB du professionnel','Abrir los datos bancarios')}</Text></TouchableOpacity><TouchableOpacity style={s.primary} onPress={()=>router.push({pathname:'/chat',params:{missionId}})}><Text style={s.primaryText}>{L('Open mission chat','Ouvrir le chat de mission','Abrir chat de misión')}</Text><Text style={s.arrow}>→</Text></TouchableOpacity><TouchableOpacity style={s.secondary} onPress={()=>router.replace('/company')}><Text style={s.secondaryText}>{L('Back to dashboard','Retour au tableau de bord','Volver al panel')}</Text></TouchableOpacity></ScrollView></SafeAreaView>}
function Row({label,value}:{label:string;value:string}){return <View style={s.row}><Text style={s.label}>{label}</Text><Text style={s.value}>{value}</Text></View>}const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.paper},container:{flexGrow:1,padding:24,paddingTop:60,paddingBottom:40,alignItems:'center'},icon:{width:72,height:72,borderRadius:36,backgroundColor:colors.greenSoft,alignItems:'center',justifyContent:'center',marginBottom:22},tick:{fontSize:34,fontWeight:'900',color:colors.green},eyebrow:{fontSize:11,fontWeight:'900',letterSpacing:1.5,color:colors.green},title:{fontSize:32,lineHeight:37,fontWeight:'800',color:colors.ink,textAlign:'center',marginTop:8},sub:{fontSize:14,lineHeight:21,color:colors.muted,textAlign:'center',marginTop:10},card:{width:'100%',backgroundColor:colors.white,borderWidth:1,borderColor:colors.line,borderRadius:radii.lg,padding:18,marginTop:25},row:{flexDirection:'row',justifyContent:'space-between',paddingVertical:12,borderBottomWidth:1,borderBottomColor:colors.line},label:{fontSize:12,color:colors.muted},value:{fontSize:13,fontWeight:'800',color:colors.ink,maxWidth:'62%',textAlign:'right'},rib:{width:'100%',minHeight:52,borderRadius:radii.md,backgroundColor:colors.companySoft,alignItems:'center',justifyContent:'center',marginTop:14},ribText:{fontSize:13,fontWeight:'900',color:colors.companyDark},primary:{width:'100%',minHeight:55,borderRadius:radii.md,backgroundColor:colors.ink,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:12,marginTop:10},primaryText:{color:colors.white,fontWeight:'800',fontSize:15},arrow:{color:colors.green,fontSize:21},secondary:{minHeight:48,justifyContent:'center'},secondaryText:{color:colors.muted,fontWeight:'700'}});
