import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { colors, radii } from '../lib/theme';

const mandatory=['ICU experience','Mechanical ventilation','Central line management','French','Spanish'];
const preferred=['Air ambulance experience','ECMO experience','International transport'];

export default function Mission(){return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.container}>
 <Pressable onPress={()=>router.back()}><Text style={styles.back}>‹ Missions</Text></Pressable>
 <Text style={styles.eyebrow}>MATCHED MISSION · 97%</Text><Text style={styles.route}>Paris → Barcelona</Text><Text style={styles.meta}>25 August · 10:30 · Commercial flight</Text>
 <View style={styles.payCard}><View><Text style={styles.payLabel}>PROFESSIONAL FEE</Text><Text style={styles.pay}>€480</Text></View><Text style={styles.covered}>+ expenses covered</Text></View>
 <Section title="Mission requirements" items={mandatory} required/><Section title="Preferred experience" items={preferred}/>
 <View style={styles.info}><Text style={styles.infoTitle}>Mission logistics</Text><Text style={styles.infoText}>Return arrangements provided · Estimated duration 8h · International mission</Text></View>
 <Pressable style={styles.button}><Text style={styles.buttonText}>Apply for mission</Text></Pressable>
 <Text style={styles.note}>Patient-identifying and clinical information is not part of this marketplace listing.</Text>
 </ScrollView></SafeAreaView>}
function Section({title,items,required=false}:{title:string;items:string[];required?:boolean}){return <View style={styles.section}><Text style={styles.sectionTitle}>{title}</Text>{items.map(x=><View key={x} style={styles.req}><View style={[styles.check,required&&styles.checkRequired]}><Text style={styles.checkText}>✓</Text></View><Text style={styles.reqText}>{x}</Text><Text style={styles.reqTag}>{required?'REQUIRED':'PREFERRED'}</Text></View>)}</View>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.paper},container:{padding:24,paddingBottom:40},back:{fontSize:15,fontWeight:'800',color:colors.ink,marginBottom:28},eyebrow:{fontSize:11,fontWeight:'800',letterSpacing:1.2,color:colors.green},route:{fontSize:38,lineHeight:42,fontWeight:'800',color:colors.ink,letterSpacing:-1.3,marginTop:10},meta:{fontSize:14,color:colors.muted,marginTop:8},payCard:{marginTop:22,padding:20,borderRadius:radii.lg,backgroundColor:colors.ink,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},payLabel:{fontSize:10,color:'#AAB2AE',fontWeight:'800',letterSpacing:1},pay:{fontSize:30,fontWeight:'800',color:colors.white,marginTop:4},covered:{fontSize:12,fontWeight:'700',color:colors.green},section:{marginTop:28},sectionTitle:{fontSize:18,fontWeight:'800',color:colors.ink,marginBottom:10},req:{backgroundColor:colors.white,borderWidth:1,borderColor:colors.line,borderRadius:14,padding:13,marginBottom:8,flexDirection:'row',alignItems:'center'},check:{width:25,height:25,borderRadius:13,backgroundColor:colors.greenSoft,alignItems:'center',justifyContent:'center'},checkRequired:{backgroundColor:colors.green},checkText:{fontWeight:'900',color:colors.ink},reqText:{flex:1,fontSize:13,fontWeight:'700',color:colors.ink,marginLeft:10},reqTag:{fontSize:8,fontWeight:'800',color:colors.muted},info:{padding:16,borderRadius:radii.md,backgroundColor:colors.greenSoft,marginTop:20},infoTitle:{fontSize:14,fontWeight:'800',color:colors.ink},infoText:{fontSize:13,lineHeight:20,color:colors.muted,marginTop:5},button:{height:56,borderRadius:radii.md,backgroundColor:colors.ink,alignItems:'center',justifyContent:'center',marginTop:24},buttonText:{color:colors.white,fontWeight:'800',fontSize:16},note:{fontSize:11,lineHeight:17,color:colors.muted,textAlign:'center',marginTop:12}});
