import { useEffect, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View, ActivityIndicator } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { supabase } from '../lib/supabase';
import { colors, radii } from '../lib/theme';

type Match = { mission_id:string; score:number; };
type Mission = { id:string; departure_location:string; destination_location:string; departure_at:string; transport_type:string; professional_type:'doctor'|'nurse'; compensation_cents:number; expenses_covered:boolean; };
export default function Missions(){
 const [items,setItems]=useState<(Mission&{score:number})[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
 useEffect(()=>{(async()=>{ if(!supabase)return; const {data:matches,error:me}=await supabase.from('mission_matches').select('mission_id,score').eq('professional_id',(await supabase.auth.getUser()).data.user?.id).eq('eligible',true).order('score',{ascending:false}); if(me){setError(me.message);setLoading(false);return;} const ids=(matches||[]).map((x:Match)=>x.mission_id); if(!ids.length){setItems([]);setLoading(false);return;} const {data,error:e}=await supabase.from('missions').select('id,departure_location,destination_location,departure_at,transport_type,professional_type,compensation_cents,expenses_covered').in('id',ids).in('status',['published','matching']).order('departure_at'); if(e)setError(e.message); else {const scoreMap=new Map((matches||[]).map((x:Match)=>[x.mission_id,Number(x.score)]));setItems(((data||[]) as Mission[]).map(m=>({...m,score:scoreMap.get(m.id)||0})));} setLoading(false);})()},[]);
 return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.container}><Pressable onPress={()=>router.back()}><Text style={styles.back}>‹ Back</Text></Pressable><Text style={styles.eyebrow}>OPEN MISSIONS</Text><Text style={styles.title}>Missions for you.</Text><Text style={styles.sub}>Verified, eligible missions ranked by your MediCrew match.</Text>{loading?<ActivityIndicator size="large" color={colors.green}/>:error?<View style={styles.error}><Text style={styles.errorText}>{error}</Text></View>:items.length===0?<View style={styles.empty}><Text style={styles.emptyTitle}>No eligible missions</Text><Text style={styles.muted}>New matching missions will appear here when your profile and availability qualify.</Text></View>:items.map(m=><Pressable key={m.id} style={styles.card} onPress={()=>router.push({pathname:'/mission',params:{id:m.id}})}><View style={styles.row}><Text style={styles.match}>{Math.round(m.score)}% MATCH</Text><Text style={styles.date}>{new Date(m.departure_at).toLocaleString()}</Text></View><Text style={styles.route}>{m.departure_location} <Text style={styles.arrow}>→</Text> {m.destination_location}</Text><Text style={styles.meta}>{m.transport_type} · {m.professional_type==='nurse'?'Nurse':'Doctor'}</Text><View style={styles.divider}/><View style={styles.row}><View><Text style={styles.pay}>€{(m.compensation_cents/100).toFixed(0)} {m.expenses_covered?'+ expenses':''}</Text><Text style={styles.muted}>Verified company</Text></View><Text style={styles.chevron}>›</Text></View></Pressable>)}</ScrollView></SafeAreaView>
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.paper},container:{padding:24,paddingBottom:40},back:{fontSize:16,fontWeight:'800',color:colors.ink,marginBottom:25},eyebrow:{fontSize:11,fontWeight:'900',letterSpacing:1.5,color:colors.green},title:{fontSize:36,fontWeight:'800',color:colors.ink,letterSpacing:-1.2,marginTop:7},sub:{fontSize:15,lineHeight:22,color:colors.muted,marginTop:10,marginBottom:22},card:{backgroundColor:colors.white,borderWidth:1,borderColor:colors.line,borderRadius:radii.lg,padding:18,marginBottom:12},row:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},match:{fontSize:10,fontWeight:'900',letterSpacing:.8,color:colors.green},date:{fontSize:11,fontWeight:'700',color:colors.muted},route:{fontSize:25,fontWeight:'800',color:colors.ink,letterSpacing:-.6,marginTop:11},arrow:{color:colors.green},meta:{fontSize:13,color:colors.muted,marginTop:5},divider:{height:1,backgroundColor:colors.line,marginVertical:15},pay:{fontSize:15,fontWeight:'800',color:colors.ink},muted:{fontSize:12,color:colors.muted,marginTop:3},chevron:{fontSize:25,color:colors.green,fontWeight:'700'},empty:{backgroundColor:colors.white,borderWidth:1,borderColor:colors.line,borderRadius:radii.lg,padding:25,alignItems:'center'},emptyTitle:{fontSize:17,fontWeight:'800',color:colors.ink},error:{backgroundColor:'#FDECEC',borderRadius:12,padding:14},errorText:{color:'#B83D3D',fontSize:12}});
