import { useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { supabase } from '../lib/supabase';
import { colors, radii } from '../lib/theme';

type Mission={id:string;title:string;departure_location:string;destination_location:string;departure_at:string;transport_type:string;professional_type:string;compensation_cents:number;status:string};
const tabs=[['upcoming','Upcoming'],['active','Active'],['completed','Completed'],['cancelled','Cancelled']] as const;
const statuses:Record<string,string[]>= {upcoming:['confirmed','professional_selected'],active:['in_progress'],completed:['completed'],cancelled:['cancelled']};
export default function MyMissions(){const [tab,setTab]=useState('upcoming');const [items,setItems]=useState<Mission[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 async function load(){if(!supabase){setError('Database unavailable');setLoading(false);return;}setLoading(true);setError('');try{const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Please sign in again');const{data:a,error:e}=await supabase.from('mission_assignments').select('mission_id').eq('professional_id',user.id);if(e)throw e;const ids=(a||[]).map(x=>x.mission_id);if(!ids.length){setItems([]);return;}const{data,error:me}=await supabase.from('missions').select('id,title,departure_location,destination_location,departure_at,transport_type,professional_type,compensation_cents,status').in('id',ids).in('status',statuses[tab]).order('departure_at',{ascending:tab!=='completed'});if(me)throw me;setItems((data||[]) as Mission[]);}catch(e:any){setError(e?.message||'Unable to load missions')}finally{setLoading(false)}}useEffect(()=>{load()},[tab]);
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.container}><Pressable onPress={()=>router.back()}><Text style={s.back}>‹ Back</Text></Pressable><Text style={s.eyebrow}>MY MISSIONS</Text><Text style={s.title}>Your missions.</Text><Text style={s.sub}>Confirmed and completed transport missions in your MediCrew history.</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.tabs}>{tabs.map(([id,label])=><Pressable key={id} onPress={()=>setTab(id)} style={[s.tab,tab===id&&s.tabActive]}><Text style={[s.tabText,tab===id&&s.tabTextActive]}>{label}</Text></Pressable>)}</ScrollView>{loading?<ActivityIndicator style={{marginTop:30}} size="large" color={colors.green}/>:error?<View style={s.error}><Text style={s.errorText}>{error}</Text><Pressable onPress={load}><Text style={s.retry}>Try again</Text></Pressable></View>:items.length===0?<View style={s.empty}><Text style={s.emptyTitle}>Nothing here yet</Text><Text style={s.emptyText}>{tab==='upcoming'?'Confirmed missions will appear here.':tab==='active'?'Your missions in progress will appear here.':tab==='completed'?'Completed missions will stay in your history.':'Cancelled missions will appear here.'}</Text></View>:items.map(m=><Pressable key={m.id} style={s.card} onPress={()=>router.push({pathname:'/mission',params:{id:m.id}})}><View style={s.row}><Text style={s.status}>{m.status.replaceAll('_',' ')}</Text><Text style={s.date}>{new Date(m.departure_at).toLocaleDateString([], {day:'2-digit',month:'short',year:'numeric'})}</Text></View><Text style={s.route}>{m.departure_location} → {m.destination_location}</Text><Text style={s.meta}>{m.transport_type} · {m.professional_type==='nurse'?'Nurse':'Doctor'}</Text><View style={s.divider}/><View style={s.row}><Text style={s.role}>{m.title}</Text><Text style={s.pay}>€{(m.compensation_cents/100).toFixed(0)}</Text></View></Pressable>)}</ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.paper},container:{padding:24,paddingBottom:50},back:{fontSize:14,fontWeight:'700',color:colors.muted,marginBottom:24},eyebrow:{fontSize:11,fontWeight:'900',letterSpacing:1.5,color:colors.green},title:{fontSize:31,fontWeight:'800',color:colors.ink,marginTop:7},sub:{fontSize:14,lineHeight:20,color:colors.muted,marginTop:7},tabs:{gap:8,paddingVertical:22},tab:{paddingHorizontal:16,paddingVertical:10,borderRadius:20,borderWidth:1,borderColor:colors.line,backgroundColor:colors.white},tabActive:{backgroundColor:colors.ink,borderColor:colors.ink},tabText:{fontSize:12,fontWeight:'700',color:colors.muted},tabTextActive:{color:colors.white},card:{backgroundColor:colors.white,borderWidth:1,borderColor:colors.line,borderRadius:radii.lg,padding:17,marginBottom:11},row:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},status:{fontSize:10,fontWeight:'900',letterSpacing:.8,color:colors.green,textTransform:'uppercase'},date:{fontSize:11,fontWeight:'700',color:colors.muted},route:{fontSize:21,fontWeight:'800',color:colors.ink,marginTop:12},meta:{fontSize:12,color:colors.muted,marginTop:5},divider:{height:1,backgroundColor:colors.line,marginVertical:14},role:{fontSize:13,fontWeight:'700',color:colors.ink,flex:1},pay:{fontSize:17,fontWeight:'800',color:colors.ink},empty:{backgroundColor:colors.white,borderWidth:1,borderColor:colors.line,borderRadius:radii.lg,padding:22},emptyTitle:{fontSize:17,fontWeight:'800',color:colors.ink},emptyText:{fontSize:13,lineHeight:19,color:colors.muted,marginTop:5},error:{backgroundColor:'#FDECEC',padding:15,borderRadius:radii.md},errorText:{color:colors.danger,fontSize:12},retry:{marginTop:8,fontWeight:'800',fontSize:12,color:colors.ink}});