import { LinearGradient } from 'expo-linear-gradient';
import { useState } from 'react';
import { Alert, Image, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router, useLocalSearchParams } from 'expo-router';
import { colors, gradients, radii } from '../lib/theme';
import { supabase } from '../lib/supabase';
import { avatarUrl, chooseAndUploadAvatar } from '../lib/avatar';
const organizationTypes=[['medical_transport','Medical transport'],['assistance','Assistance / repatriation'],['air_ambulance','Air ambulance'],['ambulance','Ambulance company'],['hospital','Hospital / clinic'],['other','Other healthcare organization']] as const;
export default function Onboarding(){
 const{role}=useLocalSearchParams<{role:'professional'|'company'}>();
 const[step,setStep]=useState(0),[type,setType]=useState<'doctor'|'nurse'>('doctor'),[name,setName]=useState(''),[location,setLocation]=useState(''),[siren,setSiren]=useState(''),[siret,setSiret]=useState(''),[organizationType,setOrganizationType]=useState('medical_transport'),[contact,setContact]=useState(''),[saving,setSaving]=useState(false),[photo,setPhoto]=useState<string|null>(null);
 const professional=role!=='company',total=professional?3:4;
 async function choosePhoto(){if(!supabase)return;try{const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Session expired');const path=await chooseAndUploadAvatar(user.id,photo);if(path)setPhoto(path)}catch(e:any){Alert.alert('Photo upload failed',e?.message||'Unable to upload photo')}}
 async function next(){
  if(step<total-1){setStep(step+1);return}
  if(!supabase)return Alert.alert('MediCrew is not configured','Connect Supabase before completing onboarding.');
  const{data:{user}}=await supabase.auth.getUser();if(!user)return Alert.alert('Session expired','Please sign in again.');
  if(!user.phone||!user.email)return Alert.alert('Account incomplete','A verified phone number and email address are required.');
  if(professional){if(!name.trim())return Alert.alert('Name required','Enter your first and last name.');if(!location.trim())return Alert.alert('Location required','Enter your starting location.');}
  else{if(!name.trim())return Alert.alert('Company name required','Enter the legal company name.');if(siret.replace(/\s/g,'').length!==14)return Alert.alert('SIRET required','Enter a valid 14-digit SIRET.');if(!contact.trim())return Alert.alert('Contact required','Enter the primary contact name.');if(!location.trim())return Alert.alert('Address required','Enter the registered company address.')}
  setSaving(true);const parts=name.trim().split(/\s+/).filter(Boolean),first=parts[0]||null,last=parts.slice(1).join(' ')||null;let error:any=null;
  const p=await supabase.from('profiles').update({first_name:first,last_name:professional?last:null,email:user.email,phone:user.phone,avatar_url:photo}).eq('id',user.id);if(p.error)error=p.error;
  if(!error&&professional){const r=await supabase.from('professionals').upsert({id:user.id,professional_type:type,available_now:false,international_available:false,country_of_operation:location.trim()},{onConflict:'id'});error=r.error}
  if(!error&&!professional){const r=await supabase.from('companies').upsert({id:user.id,company_name:name.trim(),siren:siren.replace(/\s/g,'')||null,siret:siret.replace(/\s/g,'')||null,address:location.trim(),contact_name:contact.trim(),organization_type:organizationType},{onConflict:'id'});error=r.error}
  setSaving(false);if(error)return Alert.alert('Could not save setup',error.message);
  if(professional){const{data:docs}=await supabase.from('professional_documents').select('id').eq('professional_id',user.id).in('document_type',['passport','identity']).ilike('title','%passport%').limit(1);router.replace(docs?.length?'/home':'/professional/passport?required=1')}else router.replace('/company-verification');
 }
 const title=professional?['Tell us about you.','What do you do?','Where can you operate?'][step]:['Tell us about your company.','Legal information.','Who should we contact?','Where are you based?'][step];
 return <SafeAreaView style={s.safe}><View style={s.container}><View><Text style={s.progress}>{step+1} / {total}</Text><Text style={s.title}>{title}</Text><Text style={s.subtitle}>{professional?'Your phone and email are already verified. Complete your professional identity before entering MediCrew.':'Accurate company information helps MediCrew verify organizations before they can publish missions.'}</Text></View><View>
 {professional&&step===0&&<><Text style={s.label}>Full name</Text><TextInput autoCapitalize="words" value={name} onChangeText={setName} placeholder="First and last name" style={s.input}/><PhotoChooser photo={photo} onPress={choosePhoto}/></>}
 {professional&&step===1&&<View style={s.choices}><Pressable onPress={()=>setType('doctor')} style={[s.choice,type==='doctor'&&s.active]}><Text style={s.choiceTitle}>Doctor</Text><Text style={s.choiceText}>Medical doctor</Text></Pressable><Pressable onPress={()=>setType('nurse')} style={[s.choice,type==='nurse'&&s.active]}><Text style={s.choiceTitle}>Nurse</Text><Text style={s.choiceText}>Registered nurse</Text></Pressable></View>}
 {professional&&step===2&&<><Text style={s.label}>Primary operating location</Text><TextInput value={location} onChangeText={setLocation} placeholder="City, country" style={s.input}/><Text style={s.helper}>This is used for legitimate mission matching. You can update it later.</Text></>}
 {!professional&&step===0&&<><Text style={s.label}>Legal company name</Text><TextInput autoCapitalize="words" value={name} onChangeText={setName} placeholder="Company name" style={s.input}/><Text style={[s.label,{marginTop:14}]}>Organization type</Text><View style={s.wrap}>{organizationTypes.map(([id,label])=><Pressable key={id} onPress={()=>setOrganizationType(id)} style={[s.tag,organizationType===id&&s.tagActive]}><Text style={[s.tagText,organizationType===id&&s.tagTextActive]}>{label}</Text></Pressable>)}</View></>}
 {!professional&&step===1&&<><Text style={s.label}>SIRET</Text><TextInput value={siret} onChangeText={setSiret} placeholder="14 digits" keyboardType="number-pad" maxLength={17} style={s.input}/><Text style={[s.label,{marginTop:14}]}>SIREN</Text><TextInput value={siren} onChangeText={setSiren} placeholder="9 digits (optional)" keyboardType="number-pad" maxLength={11} style={s.input}/></>}
 {!professional&&step===2&&<><Text style={s.label}>Primary contact</Text><TextInput autoCapitalize="words" value={contact} onChangeText={setContact} placeholder="Full name" style={s.input}/></>}
 {!professional&&step===3&&<><Text style={s.label}>Headquarters / registered address</Text><TextInput value={location} onChangeText={setLocation} placeholder="Address, city, country" style={s.input}/></>}
 <Pressable disabled={saving} onPress={next}><LinearGradient colors={gradients.primary} style={[s.button,saving&&{opacity:.6}]}><Text style={s.buttonText}>{saving?'Saving…':step===total-1?'Finish setup':'Continue'}</Text><Text style={s.buttonArrow}>→</Text></LinearGradient></Pressable>
 </View><Text style={s.footer}>Professional passport files are private verification documents. Companies only see the nationality and verified passport status needed for legitimate mission logistics.</Text></View></SafeAreaView>
}
function PhotoChooser({photo,onPress}:{photo:string|null;onPress:()=>void}){const url=avatarUrl(photo);return <Pressable style={s.photo} onPress={onPress}>{url?<Image source={{uri:url}} style={s.photoImage}/>:<View style={s.photoPlaceholder}><Text style={s.photoPlus}>+</Text></View>}<View style={{flex:1,marginLeft:12}}><Text style={s.photoTitle}>{url?'Profile photo added':'Add a profile photo'}</Text><Text style={s.photoSub}>Optional · you can change it later</Text></View><Text style={s.photoArrow}>›</Text></Pressable>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.paper},container:{flex:1,padding:24,justifyContent:'space-between'},progress:{fontSize:12,fontWeight:'800',color:colors.greenDark,letterSpacing:1.2},title:{fontSize:38,lineHeight:42,fontWeight:'800',color:colors.ink,letterSpacing:-1.2,marginTop:12},subtitle:{fontSize:15,lineHeight:23,color:colors.muted,marginTop:12},label:{fontSize:13,fontWeight:'700',color:colors.ink,marginBottom:8},input:{height:54,borderWidth:1,borderColor:colors.line,borderRadius:radii.md,backgroundColor:colors.white,paddingHorizontal:15,fontSize:16,color:colors.ink},photo:{marginTop:12,borderWidth:1,borderColor:colors.line,borderRadius:radii.md,backgroundColor:colors.white,padding:12,flexDirection:'row',alignItems:'center'},photoImage:{width:48,height:48,borderRadius:24},photoPlaceholder:{width:48,height:48,borderRadius:24,backgroundColor:colors.greenSoft,alignItems:'center',justifyContent:'center'},photoPlus:{fontSize:26,fontWeight:'700',color:colors.greenDark},photoTitle:{fontSize:13,fontWeight:'800',color:colors.ink},photoSub:{fontSize:10,color:colors.muted,marginTop:3},photoArrow:{fontSize:24,color:colors.greenDark},choices:{gap:12},choice:{padding:18,borderWidth:1,borderColor:colors.line,borderRadius:radii.md,backgroundColor:colors.white},active:{borderColor:colors.green,backgroundColor:colors.greenSoft},choiceTitle:{fontSize:17,fontWeight:'800',color:colors.ink},choiceText:{fontSize:13,color:colors.muted,marginTop:4},wrap:{flexDirection:'row',flexWrap:'wrap',gap:8},tag:{borderWidth:1,borderColor:colors.line,borderRadius:10,paddingHorizontal:11,paddingVertical:9,backgroundColor:colors.white},tagActive:{backgroundColor:colors.ink,borderColor:colors.ink},tagText:{fontSize:11,fontWeight:'700',color:colors.ink},tagTextActive:{color:colors.white},button:{height:56,borderRadius:radii.md,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:10,overflow:'hidden',marginTop:18},buttonText:{color:colors.white,fontSize:16,fontWeight:'800'},buttonArrow:{color:'#EFFFF8',fontSize:22,fontWeight:'900'},helper:{fontSize:12,lineHeight:18,color:colors.muted,marginTop:8},footer:{fontSize:10,lineHeight:16,color:colors.muted,textAlign:'center'}});
