import { LinearGradient } from 'expo-linear-gradient';
import { useState } from 'react';
import { Alert, Image, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router, useLocalSearchParams } from 'expo-router';
import { colors, gradients, radii } from '../lib/theme';
import { supabase } from '../lib/supabase';
import { avatarUrl, chooseAndUploadAvatar } from '../lib/avatar';

type CompanyType='transport'|'event';
export default function Onboarding(){
 const{role}=useLocalSearchParams<{role?:'professional'|'company'}>();const professional=role!=='company';
 const[step,setStep]=useState(0),[type,setType]=useState<'doctor'|'nurse'>('doctor'),[companyType,setCompanyType]=useState<CompanyType>('transport');
 const[name,setName]=useState(''),[specialty,setSpecialty]=useState(''),[years,setYears]=useState(''),[license,setLicense]=useState(''),[licenseCountry,setLicenseCountry]=useState(''),[licenseAuthority,setLicenseAuthority]=useState(''),[nationality,setNationality]=useState(''),[city,setCity]=useState(''),[country,setCountry]=useState(''),[airport,setAirport]=useState('');
 const[registrationCountry,setRegistrationCountry]=useState(''),[registrationNumber,setRegistrationNumber]=useState(''),[contact,setContact]=useState(''),[address,setAddress]=useState(''),[website,setWebsite]=useState('');
 const[photo,setPhoto]=useState<string|null>(null),[saving,setSaving]=useState(false);const total=professional?5:4;
 async function photoPick(){if(!supabase)return;const{data:{user}}=await supabase.auth.getUser();if(!user)return Alert.alert('Sign in required','Profile photos and company logos are uploaded after real authentication.');try{const path=await chooseAndUploadAvatar(user.id,photo);if(path)setPhoto(path)}catch(e:any){Alert.alert('Upload failed',e?.message||'Could not upload image')}}
 function validate(){if(professional){if(step===0&&!name.trim())return 'Enter your full legal name.';if(step===1&&(!specialty.trim()||!years.trim()))return 'Add your specialty and experience.';if(step===2&&(!license.trim()||!licenseCountry.trim()||!licenseAuthority.trim()))return 'Professional registration details are required.';if(step===3&&(!nationality.trim()||!city.trim()||!country.trim()||!airport.trim()))return 'Nationality, base city, country and airport are required.'}else{if(step===0&&!name.trim())return 'Enter the legal organization name.';if(step===1&&(!registrationCountry.trim()||!registrationNumber.trim()))return 'Country and official registration number are required.';if(step===2&&(!contact.trim()||!address.trim()))return 'Contact and registered address are required.'}return null}
 async function next(){const issue=validate();if(issue)return Alert.alert('Complete this step',issue);if(step<total-1)return setStep(v=>v+1);await finish()}
 async function finish(){if(!supabase)return Alert.alert('MediCrew is not configured');const{data:{user}}=await supabase.auth.getUser();if(!user&&__DEV__){router.replace(professional?'/home?preview=1':'/company?preview=1');return}if(!user)return Alert.alert('Session expired','Please sign in again.');setSaving(true);let error:any=null;const names=name.trim().split(/\s+/),first=names[0]||null,last=names.slice(1).join(' ')||null;const p=await supabase.from('profiles').update({first_name:first,last_name:professional?last:null,email:user.email||null,phone:user.phone||null,avatar_url:photo,city:professional?city:null,country:professional?country:registrationCountry,headline:professional?`${type==='doctor'?'Doctor':'Nurse'} · ${specialty.trim()}`:`${companyType==='transport'?'Medical transport':'Event medical staffing'} organization`}).eq('id',user.id);if(p.error)error=p.error;
 if(!error&&professional){const r=await supabase.from('professionals').upsert({id:user.id,professional_type:type,specialty:specialty.trim(),years_experience:Number(years)||0,license_number:license.trim(),license_country:licenseCountry.trim(),license_authority:licenseAuthority.trim(),nationality:nationality.trim(),country_of_operation:country.trim(),base_city:city.trim(),base_airport_code:airport.trim().toUpperCase(),verification_status:'pending',available_now:false},{onConflict:'id'});error=r.error}
 if(!error&&!professional){const r=await supabase.from('companies').upsert({id:user.id,company_name:name.trim(),company_type:companyType,company_scope:companyType,organization_type:companyType,registration_country:registrationCountry.trim(),registration_number:registrationNumber.trim(),contact_name:contact.trim(),address:address.trim(),website:website.trim()||null,verification_status:'pending'},{onConflict:'id'});error=r.error}
 setSaving(false);if(error)return Alert.alert('Could not save setup',error.message);router.replace(professional?'/professional/passport?required=1':'/company-verification')}
 const accent=professional?colors.pro:colors.company,palette=professional?gradients.professional:gradients.company;
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.container} keyboardShouldPersistTaps="handled"><Text style={[s.eyebrow,{color:accent}]}>{professional?'PROFESSIONAL':'ORGANIZATION'} · {step+1}/{total}</Text><Text style={s.title}>{professional?['Identity','Clinical profile','Professional licence','Your operating base','Verification'][step]:['Organization','Official registration','Contact details','Review'][step]}</Text><Text style={s.sub}>{professional?'Only verified doctors and nurses can access missions. Self-declared credentials never unlock work.':companyType==='transport'?'Medical transport companies publish air-transport assignments.':'Event organizations publish on-site medical staffing assignments.'}</Text><View style={s.card}>
 {professional&&step===0&&<><Field label="Full legal name" value={name} set={setName} placeholder="First and last name"/><ImagePicker value={photo} onPress={photoPick} label="Profile photo"/></>}
 {professional&&step===1&&<><Text style={s.label}>Profession</Text><View style={s.row}><Choice active={type==='doctor'} label="Doctor" onPress={()=>setType('doctor')} accent={accent}/><Choice active={type==='nurse'} label="Nurse" onPress={()=>setType('nurse')} accent={accent}/></View><Field label="Specialty" value={specialty} set={setSpecialty} placeholder="ICU, emergency medicine, anaesthesia…"/><Field label="Years of experience" value={years} set={setYears} placeholder="6" keyboard="number-pad"/></>}
 {professional&&step===2&&<><Field label="Professional licence / registration number" value={license} set={setLicense} placeholder="Official number"/><Field label="Registration country" value={licenseCountry} set={setLicenseCountry} placeholder="Country"/><Field label="Issuing authority" value={licenseAuthority} set={setLicenseAuthority} placeholder="Medical council / nursing board"/><Note text="You will still need to upload documentary evidence. MediCrew administrators must verify it before your account can accept work."/></>}
 {professional&&step===3&&<><Field label="Nationality" value={nationality} set={setNationality} placeholder="Nationality"/><Field label="Base city" value={city} set={setCity} placeholder="Paris"/><Field label="Base country" value={country} set={setCountry} placeholder="France"/><Field label="Base airport (IATA code)" value={airport} set={setAirport} placeholder="CDG" autoCapitalize="characters"/><Note text="Transport missions are suggested from your base airport. Event assignments are suggested near your base location. You can still search all eligible work with filters."/></>}
 {professional&&step===4&&<Review rows={[['Name',name],['Role',type],['Specialty',specialty],['Licence',license],['Base',`${city}, ${country} · ${airport.toUpperCase()}`],['Nationality',nationality]]}/>} 
 {!professional&&step===0&&<><Field label="Legal organization name" value={name} set={setName} placeholder="Organization name"/><ImagePicker value={photo} onPress={photoPick} label="Company logo"/><Text style={s.label}>What does your company do?</Text><Choice active={companyType==='transport'} label="Medical transport" sub="Air medical transport / repatriation missions" onPress={()=>setCompanyType('transport')} accent={accent}/><View style={{height:10}}/><Choice active={companyType==='event'} label="Event medical staffing" sub="Medical teams for events and productions" onPress={()=>setCompanyType('event')} accent={accent}/></>}
 {!professional&&step===1&&<><Field label="Country / jurisdiction of registration" value={registrationCountry} set={setRegistrationCountry} placeholder="Country"/><Field label="Official registration number" value={registrationNumber} set={setRegistrationNumber} placeholder="Company / organization number"/><Note text="MediCrew is international. We do not require SIRET or SIREN; use the official registration identifier issued in your jurisdiction."/></>}
 {!professional&&step===2&&<><Field label="Primary contact" value={contact} set={setContact} placeholder="Full name"/><Field label="Registered address" value={address} set={setAddress} placeholder="Address, city, country"/><Field label="Website (optional)" value={website} set={setWebsite} placeholder="https://…" autoCapitalize="none"/></>}
 {!professional&&step===3&&<Review rows={[['Organization',name],['Type',companyType==='transport'?'Medical transport':'Event medical staffing'],['Registration',`${registrationCountry} · ${registrationNumber}`],['Contact',contact],['Address',address]]}/>} 
 </View><View style={s.actions}>{step>0&&<Pressable onPress={()=>setStep(v=>v-1)} style={s.back}><Text style={s.backText}>← Back</Text></Pressable>}<Pressable onPress={next} disabled={saving} style={{flex:1}}><LinearGradient colors={palette} style={s.button}><Text style={s.buttonText}>{saving?'Saving…':step===total-1?'Submit for verification':'Continue'}</Text></LinearGradient></Pressable></View></ScrollView></SafeAreaView>
}
function Field({label,value,set,placeholder,keyboard,autoCapitalize='words'}:{label:string;value:string;set:(v:string)=>void;placeholder:string;keyboard?:any;autoCapitalize?:any}){return <View style={s.field}><Text style={s.label}>{label}</Text><TextInput value={value} onChangeText={set} placeholder={placeholder} keyboardType={keyboard} autoCapitalize={autoCapitalize} style={s.input}/></View>}
function Choice({active,label,sub,onPress,accent}:{active:boolean;label:string;sub?:string;onPress:()=>void;accent:string}){return <Pressable onPress={onPress} style={[s.choice,active&&{borderColor:accent,backgroundColor:accent+'12'}]}><View style={[s.radio,active&&{borderColor:accent}]}>{active?<View style={[s.radioIn,{backgroundColor:accent}]}/>:null}</View><View style={{flex:1}}><Text style={s.choiceTitle}>{label}</Text>{sub?<Text style={s.choiceSub}>{sub}</Text>:null}</View></Pressable>}
function ImagePicker({value,onPress,label}:{value:string|null;onPress:()=>void;label:string}){const url=avatarUrl(value);return <Pressable onPress={onPress} style={s.imagePick}>{url?<Image source={{uri:url}} style={s.image}/>:<View style={s.imageEmpty}><Text style={s.imagePlus}>＋</Text></View>}<View><Text style={s.choiceTitle}>{label}</Text><Text style={s.choiceSub}>JPG, PNG or WEBP</Text></View></Pressable>}
function Note({text}:{text:string}){return <View style={s.note}><Text style={s.noteText}>{text}</Text></View>}
function Review({rows}:{rows:string[][]}){return <View>{rows.map(([a,b])=><View style={s.review} key={a}><Text style={s.reviewKey}>{a}</Text><Text style={s.reviewValue}>{b||'—'}</Text></View>)}</View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.paper},container:{padding:24,paddingBottom:42},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:1.4},title:{fontSize:36,fontWeight:'900',color:colors.ink,marginTop:8},sub:{fontSize:14,lineHeight:21,color:colors.muted,marginTop:8,marginBottom:20},card:{backgroundColor:colors.white,borderWidth:1,borderColor:colors.line,borderRadius:radii.lg,padding:18},field:{marginBottom:14},label:{fontSize:12,fontWeight:'800',color:colors.ink,marginBottom:7},input:{height:52,borderWidth:1,borderColor:colors.line,borderRadius:radii.md,paddingHorizontal:14,fontSize:15,color:colors.ink,backgroundColor:colors.paper},row:{flexDirection:'row',gap:10,marginBottom:14},choice:{flex:1,minHeight:62,borderWidth:1.5,borderColor:colors.line,borderRadius:radii.md,padding:13,flexDirection:'row',alignItems:'center',gap:11},radio:{width:21,height:21,borderRadius:11,borderWidth:2,borderColor:colors.line,alignItems:'center',justifyContent:'center'},radioIn:{width:11,height:11,borderRadius:6},choiceTitle:{fontSize:14,fontWeight:'900',color:colors.ink},choiceSub:{fontSize:10.5,lineHeight:15,color:colors.muted,marginTop:3},imagePick:{flexDirection:'row',alignItems:'center',gap:12,borderWidth:1,borderColor:colors.line,borderRadius:radii.md,padding:11,marginBottom:15},image:{width:52,height:52,borderRadius:16},imageEmpty:{width:52,height:52,borderRadius:16,backgroundColor:colors.greenSoft,alignItems:'center',justifyContent:'center'},imagePlus:{fontSize:24,color:colors.greenDark,fontWeight:'900'},note:{padding:13,borderRadius:radii.md,backgroundColor:colors.greenSoft},noteText:{fontSize:11.5,lineHeight:17,color:colors.greenDark},review:{flexDirection:'row',justifyContent:'space-between',gap:15,paddingVertical:10,borderBottomWidth:1,borderBottomColor:colors.line},reviewKey:{fontSize:12,color:colors.muted},reviewValue:{flex:1,fontSize:12,fontWeight:'800',color:colors.ink,textAlign:'right'},actions:{flexDirection:'row',alignItems:'center',gap:10,marginTop:16},back:{paddingHorizontal:12,height:54,justifyContent:'center'},backText:{fontSize:13,fontWeight:'800',color:colors.muted},button:{height:54,borderRadius:radii.md,alignItems:'center',justifyContent:'center'},buttonText:{color:colors.white,fontSize:14,fontWeight:'900'}});