import { LinearGradient } from 'expo-linear-gradient';
import { useState } from 'react';
import { Alert,Image,Pressable,ScrollView,StyleSheet,Text,TextInput,View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router,useLocalSearchParams } from 'expo-router';
import { colors,gradients,radii } from '../lib/theme';
import { supabase } from '../lib/supabase';
import { avatarUrl,chooseAndUploadAvatar } from '../lib/avatar';
import { usePreferences } from '../lib/preferences-context';
import { localize } from '../lib/i18n';

type CompanyType='transport'|'event';
export default function Onboarding(){
 const prefs=usePreferences();const L=(en:string,fr:string,es:string)=>localize(prefs.language,en,fr,es);const{role}=useLocalSearchParams<{role?:'professional'|'company'}>();const professional=role!=='company';
 const[step,setStep]=useState(0),[type,setType]=useState<'doctor'|'nurse'>('doctor'),[companyType,setCompanyType]=useState<CompanyType>('transport');
 const[name,setName]=useState(''),[bio,setBio]=useState(''),[years,setYears]=useState(''),[license,setLicense]=useState(''),[licenseCountry,setLicenseCountry]=useState(''),[licenseAuthority,setLicenseAuthority]=useState(''),[nationality,setNationality]=useState(''),[city,setCity]=useState(''),[country,setCountry]=useState(''),[airport,setAirport]=useState('');
 const[registrationCountry,setRegistrationCountry]=useState(''),[registrationNumber,setRegistrationNumber]=useState(''),[contact,setContact]=useState(''),[address,setAddress]=useState(''),[website,setWebsite]=useState('');
 const[photo,setPhoto]=useState<string|null>(null),[saving,setSaving]=useState(false);const total=4;
 async function photoPick(){if(!supabase)return;const{data:{user}}=await supabase.auth.getUser();if(!user)return Alert.alert(L('Sign in required','Connexion requise','Inicio de sesión obligatorio'));try{const path=await chooseAndUploadAvatar(user.id,photo);if(path)setPhoto(path)}catch(e:any){Alert.alert(L('Upload failed','Échec de l’envoi','Falló la carga'),e?.message||'MediCrew')}}
 function validate(){if(professional){if(step===0&&(!name.trim()||!bio.trim()))return L('Add your legal name and a short bio.','Ajoutez votre nom légal et une courte bio.','Añade tu nombre legal y una breve bio.');if(step===1&&!years.trim())return L('Add your years of professional experience.','Ajoutez vos années d’expérience professionnelle.','Añade tus años de experiencia profesional.');if(step===2&&(!license.trim()||!licenseCountry.trim()||!licenseAuthority.trim()))return L('Professional registration details are required.','Les informations d’inscription professionnelle sont requises.','Se requieren los datos de registro profesional.');if(step===3&&(!nationality.trim()||!city.trim()||!country.trim()||!airport.trim()))return L('Nationality, base city, country and airport are required.','Nationalité, ville, pays et aéroport de base sont requis.','Se requieren nacionalidad, ciudad, país y aeropuerto base.')}else{if(step===0&&(!name.trim()||!bio.trim()))return L('Add the organization name and a short bio.','Ajoutez le nom de l’organisation et une courte bio.','Añade el nombre de la organización y una breve bio.');if(step===1&&(!registrationCountry.trim()||!registrationNumber.trim()))return L('Country and official registration number are required.','Le pays et le numéro officiel d’immatriculation sont requis.','Se requieren el país y el número oficial de registro.');if(step===2&&(!contact.trim()||!address.trim()))return L('Contact and registered address are required.','Le contact et l’adresse enregistrée sont requis.','Se requieren el contacto y la dirección registrada.')}return null}
 async function next(){const issue=validate();if(issue)return Alert.alert(L('Complete this step','Complétez cette étape','Completa este paso'),issue);if(step<total-1)return setStep(v=>v+1);await finish()}
 async function finish(){if(!supabase)return;const{data:{user}}=await supabase.auth.getUser();if(!user)return Alert.alert(L('Session expired','Session expirée','Sesión caducada'));setSaving(true);let error:any=null;const names=name.trim().split(/\s+/),first=names[0]||null,last=names.slice(1).join(' ')||null;const headline=professional?`${type==='doctor'?'Doctor':'Nurse'} · ${Number(years)||0} years experience`:`${companyType==='transport'?'Medical transport':'Event medical staffing'} organization`;const p=await supabase.from('profiles').update({first_name:first,last_name:professional?last:null,avatar_url:photo,bio:bio.trim(),city:professional?city:null,country:professional?country:registrationCountry,headline}).eq('id',user.id);if(p.error)error=p.error;
 if(!error&&professional){const r=await supabase.from('professionals').upsert({id:user.id,professional_type:type,specialty:null,years_experience:Number(years)||0,license_number:license.trim(),license_country:licenseCountry.trim(),license_authority:licenseAuthority.trim(),nationality:nationality.trim(),country_of_operation:country.trim(),base_city:city.trim(),base_airport_code:airport.trim().toUpperCase(),verification_status:'pending',available_now:false},{onConflict:'id'});error=r.error}
 if(!error&&!professional){const r=await supabase.from('companies').upsert({id:user.id,company_name:name.trim(),company_type:companyType,company_scope:companyType,organization_type:companyType,registration_country:registrationCountry.trim(),registration_number:registrationNumber.trim(),contact_name:contact.trim(),address:address.trim(),website:website.trim()||null,verification_status:'pending'},{onConflict:'id'});error=r.error}
 setSaving(false);if(error)return Alert.alert(L('Could not save setup','Impossible d’enregistrer','No se pudo guardar'),error.message);router.replace(professional?'/professional/passport?required=1':'/company-verification')}
 const accent=professional?colors.pro:colors.company,palette=professional?gradients.professional:gradients.company;const steps=professional?[L('Your profile','Votre profil','Tu perfil'),L('Experience','Expérience','Experiencia'),L('Professional registration','Inscription professionnelle','Registro profesional'),L('Operating base','Base opérationnelle','Base operativa')]:[L('Organization','Organisation','Organización'),L('Official registration','Immatriculation officielle','Registro oficial'),L('Contact details','Coordonnées','Datos de contacto'),L('Review','Vérification','Revisión')];
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.container} keyboardShouldPersistTaps="handled"><Text style={[s.eyebrow,{color:accent}]}>{professional?prefs.tr('professional').toUpperCase():prefs.tr('organization').toUpperCase()} · {step+1}/{total}</Text><Text style={s.title}>{steps[step]}</Text><Text style={s.sub}>{professional?L('Your public profile helps organizations understand who you are. Official registration details are reviewed separately.','Votre profil public aide les entreprises à comprendre qui vous êtes. Les références officielles sont vérifiées séparément.','Tu perfil público ayuda a las empresas a conocerte. Las referencias oficiales se revisan por separado.'):L('Build a clear organization profile. Official registration references are reviewed before access is approved.','Créez un profil entreprise clair. Les références officielles sont vérifiées avant validation.','Crea un perfil claro. Las referencias oficiales se revisan antes de aprobar el acceso.')}</Text><View style={s.card}>
 {professional&&step===0&&<><Field label={L('Full legal name','Nom légal complet','Nombre legal completo')} value={name} set={setName} placeholder={L('First and last name','Prénom et nom','Nombre y apellidos')}/><Multiline label={L('Bio','Bio','Bio')} value={bio} set={setBio} placeholder={L('Briefly introduce your professional background and the kind of missions you are looking for.','Présentez brièvement votre parcours et les missions que vous recherchez.','Presenta brevemente tu trayectoria y las misiones que buscas.')}/><ImagePicker value={photo} onPress={photoPick} label={L('Profile photo','Photo de profil','Foto de perfil')}/></>}
 {professional&&step===1&&<><Text style={s.label}>{L('Profession','Profession','Profesión')}</Text><View style={s.row}><Choice active={type==='doctor'} label={prefs.tr('doctor')} onPress={()=>setType('doctor')} accent={accent}/><Choice active={type==='nurse'} label={prefs.tr('nurse')} onPress={()=>setType('nurse')} accent={accent}/></View><Field label={L('Years of experience','Années d’expérience','Años de experiencia')} value={years} set={setYears} placeholder="6" keyboard="number-pad"/></>}
 {professional&&step===2&&<><Field label={L('Professional registration number','Numéro d’inscription professionnelle','Número de registro profesional')} value={license} set={setLicense} placeholder={L('Official number','Numéro officiel','Número oficial')}/><Field label={L('Registration country','Pays d’inscription','País de registro')} value={licenseCountry} set={setLicenseCountry} placeholder={L('Country','Pays','País')}/><Field label={L('Issuing authority','Autorité émettrice','Autoridad emisora')} value={licenseAuthority} set={setLicenseAuthority} placeholder="Medical council / nursing board"/><Note text={L('MediCrew will verify the official reference with the relevant authority. No large file upload is required.','MediCrew vérifiera la référence officielle auprès de l’autorité compétente. Aucun gros fichier n’est requis.','MediCrew verificará la referencia oficial con la autoridad correspondiente. No se requiere un archivo pesado.')}/></>}
 {professional&&step===3&&<><Field label={L('Nationality','Nationalité','Nacionalidad')} value={nationality} set={setNationality} placeholder={L('Nationality','Nationalité','Nacionalidad')}/><Field label={L('Base city','Ville de base','Ciudad base')} value={city} set={setCity} placeholder="Paris"/><Field label={L('Base country','Pays de base','País base')} value={country} set={setCountry} placeholder="France"/><Field label={L('Base airport (IATA)','Aéroport de base (IATA)','Aeropuerto base (IATA)')} value={airport} set={setAirport} placeholder="CDG" autoCapitalize="characters"/></>}
 {!professional&&step===0&&<><Field label={L('Legal organization name','Nom légal de l’organisation','Nombre legal de la organización')} value={name} set={setName} placeholder={prefs.tr('organization')}/><Multiline label={L('Bio','Bio','Bio')} value={bio} set={setBio} placeholder={L('Describe your organization, activity and the type of medical professionals you work with.','Décrivez votre organisation, votre activité et les professionnels médicaux avec lesquels vous travaillez.','Describe tu organización, actividad y los profesionales médicos con los que trabajas.')}/><ImagePicker value={photo} onPress={photoPick} label={L('Company logo','Logo de l’entreprise','Logo de la empresa')}/><Text style={s.label}>{L('Organization type','Type d’organisation','Tipo de organización')}</Text><Choice active={companyType==='transport'} label={L('Medical transport','Transport médical','Transporte médico')} onPress={()=>setCompanyType('transport')} accent={accent}/><View style={{height:9}}/><Choice active={companyType==='event'} label={L('Event medical staffing','Médical événementiel','Personal médico para eventos')} onPress={()=>setCompanyType('event')} accent={accent}/></>}
 {!professional&&step===1&&<><Field label={L('Country / jurisdiction of registration','Pays / juridiction d’immatriculation','País / jurisdicción de registro')} value={registrationCountry} set={setRegistrationCountry} placeholder={L('Country','Pays','País')}/><Field label={L('Official registration number','Numéro officiel d’immatriculation','Número oficial de registro')} value={registrationNumber} set={setRegistrationNumber} placeholder={L('Official registry identifier','Identifiant officiel du registre','Identificador oficial del registro')}/></>}
 {!professional&&step===2&&<><Field label={L('Primary contact','Contact principal','Contacto principal')} value={contact} set={setContact} placeholder={L('Full name','Nom complet','Nombre completo')}/><Field label={L('Registered address','Adresse enregistrée','Dirección registrada')} value={address} set={setAddress} placeholder={L('Address, city, country','Adresse, ville, pays','Dirección, ciudad, país')}/><Field label={L('Website (optional)','Site web (optionnel)','Sitio web (opcional)')} value={website} set={setWebsite} placeholder="https://…" autoCapitalize="none"/></>}
 {!professional&&step===3&&<Review rows={[[prefs.tr('organization'),name],[L('Type','Type','Tipo'),companyType],[L('Registration','Immatriculation','Registro'),`${registrationCountry} · ${registrationNumber}`],[L('Contact','Contact','Contacto'),contact]]}/>} 
 </View><View style={s.actions}>{step>0&&<Pressable onPress={()=>setStep(v=>v-1)} style={s.back}><Text style={s.backText}>← {prefs.tr('back')}</Text></Pressable>}<Pressable onPress={next} disabled={saving} style={{flex:1}}><LinearGradient colors={palette} style={s.button}><Text style={s.buttonText}>{saving?L('Saving…','Enregistrement…','Guardando…'):step===total-1?L('Continue to verification','Continuer vers la vérification','Continuar a verificación'):L('Continue','Continuer','Continuar')}</Text></LinearGradient></Pressable></View></ScrollView></SafeAreaView>
}
function Field({label,value,set,placeholder,keyboard,autoCapitalize='words'}:{label:string;value:string;set:(v:string)=>void;placeholder:string;keyboard?:any;autoCapitalize?:any}){return <View style={s.field}><Text style={s.label}>{label}</Text><TextInput value={value} onChangeText={set} placeholder={placeholder} keyboardType={keyboard} autoCapitalize={autoCapitalize} style={s.input}/></View>}
function Multiline({label,value,set,placeholder}:{label:string;value:string;set:(v:string)=>void;placeholder:string}){return <View style={s.field}><Text style={s.label}>{label}</Text><TextInput value={value} onChangeText={set} placeholder={placeholder} multiline maxLength={500} style={[s.input,s.multi]}/><Text style={s.counter}>{value.length}/500</Text></View>}
function Choice({active,label,onPress,accent}:{active:boolean;label:string;onPress:()=>void;accent:string}){return <Pressable onPress={onPress} style={[s.choice,active&&{borderColor:accent,backgroundColor:accent+'12'}]}><Text style={s.choiceTitle}>{label}</Text></Pressable>}
function ImagePicker({value,onPress,label}:{value:string|null;onPress:()=>void;label:string}){const url=avatarUrl(value);return <Pressable onPress={onPress} style={s.imagePick}>{url?<Image source={{uri:url}} style={s.image}/>:<View style={s.imageEmpty}><Text style={s.imagePlus}>＋</Text></View>}<View><Text style={s.choiceTitle}>{label}</Text><Text style={s.choiceSub}>JPG, PNG or WEBP</Text></View></Pressable>}
function Note({text}:{text:string}){return <View style={s.note}><Text style={s.noteText}>{text}</Text></View>}
function Review({rows}:{rows:string[][]}){return <View>{rows.map(([a,b])=><View key={a} style={s.review}><Text style={s.reviewLabel}>{a}</Text><Text style={s.reviewValue}>{b||'—'}</Text></View>)}</View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.paper},container:{padding:22,paddingBottom:45},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:1.3},title:{fontSize:34,fontWeight:'900',color:colors.ink,marginTop:7},sub:{fontSize:13,lineHeight:20,color:colors.muted,marginTop:8},card:{marginTop:20,backgroundColor:colors.white,borderWidth:1,borderColor:colors.line,borderRadius:radii.lg,padding:17},field:{marginBottom:14},label:{fontSize:11,fontWeight:'800',color:colors.ink,marginBottom:7},input:{minHeight:50,borderWidth:1,borderColor:colors.line,borderRadius:radii.md,paddingHorizontal:13,color:colors.ink,backgroundColor:colors.paper},multi:{height:110,textAlignVertical:'top',paddingTop:12},counter:{fontSize:9,color:colors.muted,textAlign:'right',marginTop:4},row:{flexDirection:'row',gap:8},choice:{flex:1,minHeight:48,borderWidth:1,borderColor:colors.line,borderRadius:radii.md,alignItems:'center',justifyContent:'center',padding:11},choiceTitle:{fontSize:12.5,fontWeight:'900',color:colors.ink},choiceSub:{fontSize:10,color:colors.muted,marginTop:3},imagePick:{flexDirection:'row',gap:12,alignItems:'center',borderWidth:1,borderColor:colors.line,borderRadius:radii.md,padding:12,marginBottom:14},image:{width:52,height:52,borderRadius:16},imageEmpty:{width:52,height:52,borderRadius:16,backgroundColor:colors.line,alignItems:'center',justifyContent:'center'},imagePlus:{fontSize:25,color:colors.muted},note:{padding:12,borderRadius:radii.md,backgroundColor:colors.proSoft,marginTop:5},noteText:{fontSize:11,lineHeight:17,color:colors.ink},actions:{flexDirection:'row',gap:9,marginTop:16},back:{height:54,paddingHorizontal:16,borderWidth:1,borderColor:colors.line,borderRadius:radii.md,alignItems:'center',justifyContent:'center'},backText:{fontSize:12,fontWeight:'800',color:colors.ink},button:{height:54,borderRadius:radii.md,alignItems:'center',justifyContent:'center'},buttonText:{fontSize:13,fontWeight:'900',color:colors.white},review:{paddingVertical:10,borderBottomWidth:1,borderBottomColor:colors.line},reviewLabel:{fontSize:10,color:colors.muted},reviewValue:{fontSize:13,fontWeight:'800',color:colors.ink,marginTop:3}});