import { useEffect,useState } from 'react';
import { ActivityIndicator,Pressable,ScrollView,StyleSheet,Text,View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { supabase } from '../lib/supabase';
import { colors,radii } from '../lib/theme';

type State={authenticated?:boolean;role?:'professional'|'company'|'admin';status?:string;allowed?:boolean;email?:string;submitted_at?:string|null};
export default function PendingReview(){const[state,setState]=useState<State|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');useEffect(()=>{void load();const c=supabase;if(!c)return;const channel=c.channel('account-review-live').on('postgres_changes',{event:'UPDATE',schema:'public',table:'professionals'},()=>void load()).on('postgres_changes',{event:'UPDATE',schema:'public',table:'companies'},()=>void load()).subscribe();const timer=setInterval(()=>void load(),15000);return()=>{clearInterval(timer);void c.removeChannel(channel)}},[]);
async function load(){const c=supabase;if(!c){setError('MediCrew is not configured');setLoading(false);return}const{data,error:e}=await c.rpc('my_account_access_state');if(e){setError(e.message);setLoading(false);return}const next=(data||{}) as State;setState(next);setLoading(false);if(next.allowed){router.replace(next.role==='company'?'/company':next.role==='admin'?'/admin':'/home')}}
async function signOut(){if(supabase)await supabase.auth.signOut();router.replace('/')}
if(loading)return <SafeAreaView style={s.safe}><ActivityIndicator style={{marginTop:100}} size="large" color={colors.green}/></SafeAreaView>;
const rejected=state?.status==='rejected',suspended=state?.status==='suspended',incomplete=state?.status==='incomplete';const accent=state?.role==='company'?colors.companyDark:colors.proDark;return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.container}><View style={[s.icon,{backgroundColor:accent+'18'}]}><Text style={[s.iconText,{color:accent}]}>{rejected?'!':suspended?'×':'✓'}</Text></View><Text style={s.eyebrow}>MEDICREW VERIFICATION</Text><Text style={s.title}>{rejected?'Your profile needs changes.':suspended?'Access suspended.':incomplete?'Finish your profile.':'Your profile has been created.'}</Text><Text style={s.text}>{rejected?'Our team could not approve the current evidence. Review your documents and submit corrected evidence, then resubmit your profile.':suspended?'Your verified-network access is currently suspended. Contact MediCrew support for details.':incomplete?'Complete the required identity and verification steps before submitting your account for review.':<>The MediCrew team is reviewing your profile and documents. We will send an email to <Text style={s.email}>{state?.email||'your verified email address'}</Text> and a notification as soon as the review is complete.</>}</Text>{!rejected&&!suspended&&!incomplete?<View style={s.eta}><Text style={s.etaBig}>≤ 24h</Text><Text style={s.etaText}>Review usually completes within 24 hours. You do not have access to missions, the verified network or messaging until approval.</Text></View>:null}{error?<Text style={s.error}>{error}</Text>:null}<Pressable onPress={()=>void load()} style={[s.primary,{backgroundColor:accent}]}><Text style={s.primaryText}>Check review status</Text></Pressable>{(rejected||incomplete)&&state?.role==='professional'?<Pressable onPress={()=>router.replace('/professional/passport?required=1')} style={s.secondary}><Text style={s.secondaryText}>Review professional evidence</Text></Pressable>:null}{(rejected||incomplete)&&state?.role==='company'?<Pressable onPress={()=>router.replace('/company-verification')} style={s.secondary}><Text style={s.secondaryText}>Review organization evidence</Text></Pressable>:null}<Pressable onPress={signOut} style={s.logout}><Text style={s.logoutText}>Log out</Text></Pressable><Text style={s.note}>For security, account access is controlled by MediCrew verification status on the server, not only by this screen.</Text></ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.paper},container:{padding:26,paddingTop:70,paddingBottom:50},icon:{width:68,height:68,borderRadius:24,alignItems:'center',justifyContent:'center'},iconText:{fontSize:31,fontWeight:'900'},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:1.4,color:colors.greenDark,marginTop:24},title:{fontSize:35,lineHeight:39,fontWeight:'900',color:colors.ink,marginTop:8},text:{fontSize:14,lineHeight:22,color:colors.muted,marginTop:12},email:{fontWeight:'900',color:colors.ink},eta:{marginTop:24,padding:18,borderRadius:radii.lg,backgroundColor:colors.white,borderWidth:1,borderColor:colors.line},etaBig:{fontSize:27,fontWeight:'900',color:colors.ink},etaText:{fontSize:11.5,lineHeight:18,color:colors.muted,marginTop:5},primary:{height:54,borderRadius:radii.md,alignItems:'center',justifyContent:'center',marginTop:22},primaryText:{fontSize:14,fontWeight:'900',color:colors.white},secondary:{height:52,borderRadius:radii.md,borderWidth:1,borderColor:colors.line,backgroundColor:colors.white,alignItems:'center',justifyContent:'center',marginTop:10},secondaryText:{fontSize:13,fontWeight:'900',color:colors.ink},logout:{alignItems:'center',padding:17},logoutText:{fontSize:12,fontWeight:'800',color:colors.muted},note:{fontSize:9.5,lineHeight:15,color:colors.muted,textAlign:'center',marginTop:8},error:{fontSize:11.5,color:colors.danger,marginTop:12}});