import { useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { colors, radii } from '../lib/theme';
import { Currency, Language, supportedCurrencies, supportedLanguages } from '../lib/i18n';
import { usePreferences } from '../lib/preferences-context';

export default function Preferences(){const prefs=usePreferences();const[language,setLanguage]=useState<Language>(prefs.language);const[currency,setCurrency]=useState<Currency>(prefs.currency);const[saving,setSaving]=useState(false);useEffect(()=>{setLanguage(prefs.language);setCurrency(prefs.currency)},[prefs.language,prefs.currency]);async function save(){setSaving(true);try{await prefs.save(language,currency);Alert.alert(prefs.tr('saved'));router.back()}catch(e:any){Alert.alert('MediCrew',e?.message||'Unable to save preferences')}finally{setSaving(false)}}if(!prefs.ready)return <SafeAreaView style={s.safe}><ActivityIndicator style={{marginTop:80}} color={colors.pro}/></SafeAreaView>;return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.container}><Pressable onPress={()=>router.back()}><Text style={s.back}>←</Text></Pressable><Text style={s.eyebrow}>MEDICREW · {prefs.tr('preferences').toUpperCase()}</Text><Text style={s.title}>{prefs.tr('settings')}</Text><Text style={s.section}>{prefs.tr('language')}</Text><View style={s.card}>{supportedLanguages.map(x=><Pressable key={x.code} onPress={()=>setLanguage(x.code)} style={[s.option,language===x.code&&s.selected]}><View><Text style={s.optionTitle}>{x.label}</Text><Text style={s.optionSub}>{x.code==='en'?'English':x.code==='fr'?'Français':'Español'}</Text></View><View style={[s.radio,language===x.code&&s.radioOn]}>{language===x.code?<View style={s.dot}/>:null}</View></Pressable>)}</View><Text style={s.section}>{prefs.tr('currency')}</Text><View style={s.card}>{supportedCurrencies.map(x=><Pressable key={x.code} onPress={()=>setCurrency(x.code)} style={[s.option,currency===x.code&&s.selected]}><View><Text style={s.optionTitle}>{x.code}</Text><Text style={s.optionSub}>{x.label}</Text></View><Text style={s.symbol}>{x.symbol}</Text></Pressable>)}</View><Text style={s.note}>{prefs.tr('currencyNote')}</Text><Pressable disabled={saving} onPress={save} style={[s.save,saving&&{opacity:.6}]}>{saving?<ActivityIndicator color={colors.white}/>:<Text style={s.saveText}>{prefs.tr('save')}</Text>}</Pressable></ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.paper},container:{padding:22,paddingBottom:50},back:{fontSize:28,color:colors.ink},eyebrow:{fontSize:10,fontWeight:'900',letterSpacing:1.2,color:colors.pro,marginTop:18},title:{fontSize:32,fontWeight:'900',color:colors.ink,marginTop:5},section:{fontSize:16,fontWeight:'900',color:colors.ink,marginTop:26,marginBottom:9},card:{backgroundColor:colors.white,borderWidth:1,borderColor:colors.line,borderRadius:radii.lg,overflow:'hidden'},option:{minHeight:64,paddingHorizontal:16,paddingVertical:12,flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderBottomWidth:1,borderBottomColor:colors.line},selected:{backgroundColor:colors.proSoft},optionTitle:{fontSize:14,fontWeight:'900',color:colors.ink},optionSub:{fontSize:10.5,color:colors.muted,marginTop:2},radio:{width:20,height:20,borderRadius:10,borderWidth:2,borderColor:colors.line,alignItems:'center',justifyContent:'center'},radioOn:{borderColor:colors.pro},dot:{width:10,height:10,borderRadius:5,backgroundColor:colors.pro},symbol:{fontSize:16,fontWeight:'900',color:colors.proDark},note:{fontSize:11,lineHeight:17,color:colors.muted,marginTop:10},save:{marginTop:28,minHeight:54,borderRadius:radii.md,backgroundColor:colors.ink,alignItems:'center',justifyContent:'center'},saveText:{fontSize:13,fontWeight:'900',color:colors.white}});