import { useEffect, useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { colors, radii } from '../lib/theme';
import { supabase } from '../lib/supabase';
import { usePreferences } from '../lib/preferences-context';
import { localize } from '../lib/i18n';

export default function ResetPassword(){const prefs=usePreferences();const L=(en:string,fr:string,es:string)=>localize(prefs.language,en,fr,es);const[password,setPassword]=useState('');const[confirm,setConfirm]=useState('');const[show,setShow]=useState(false);const[loading,setLoading]=useState(false);const[ready,setReady]=useState(false);useEffect(()=>{let mounted=true;supabase?.auth.getSession().then(({data})=>{if(mounted)setReady(Boolean(data.session));});const sub=supabase?.auth.onAuthStateChange((event,session)=>{if(mounted&&(event==='PASSWORD_RECOVERY'||session))setReady(true)});return()=>{mounted=false;sub?.data.subscription.unsubscribe()};},[]);async function save(){if(!supabase)return;if(!ready)return Alert.alert(L('Reset link required','Lien de réinitialisation requis','Se requiere enlace de restablecimiento'),L('Open the password reset link from your email before choosing a new password.','Ouvrez le lien reçu par email avant de choisir un nouveau mot de passe.','Abre el enlace de restablecimiento del correo antes de elegir una nueva contraseña.'));if(password.length<8||!/[A-Z]/.test(password)||!/[a-z]/.test(password)||!/\d/.test(password))return Alert.alert(L('Password too weak','Mot de passe trop faible','Contraseña demasiado débil'),L('Use at least 8 characters with uppercase, lowercase and a number.','Utilisez au moins 8 caractères avec majuscule, minuscule et chiffre.','Usa al menos 8 caracteres con mayúscula, minúscula y número.'));if(password!==confirm)return Alert.alert(L('Passwords do not match','Les mots de passe ne correspondent pas','Las contraseñas no coinciden'));setLoading(true);const{error}=await supabase.auth.updateUser({password});setLoading(false);if(error)return Alert.alert(L('Could not update password','Impossible de modifier le mot de passe','No se pudo actualizar la contraseña'),error.message);await supabase.auth.signOut();Alert.alert(L('Password updated','Mot de passe mis à jour','Contraseña actualizada'));router.replace('/auth')}
 return <SafeAreaView style={s.safe}><View style={s.container}><Text style={s.eyebrow}>{L('NEW PASSWORD','NOUVEAU MOT DE PASSE','NUEVA CONTRASEÑA')}</Text><Text style={s.title}>{L('Choose a new password.','Choisissez un nouveau mot de passe.','Elige una nueva contraseña.')}</Text><Text style={s.sub}>{ready?L('Use a strong password you do not reuse elsewhere.','Utilisez un mot de passe fort que vous ne réutilisez pas ailleurs.','Usa una contraseña segura que no reutilices en otros sitios.'):L('Open the secure reset link from your email to continue.','Ouvrez le lien sécurisé reçu par email pour continuer.','Abre el enlace seguro del correo para continuar.')}</Text><View style={s.card}><Text style={s.label}>{L('New password','Nouveau mot de passe','Nueva contraseña')}</Text><View style={s.password}><TextInput secureTextEntry={!show} value={password} onChangeText={setPassword} style={s.passInput} editable={ready}/><Pressable onPress={()=>setShow(v=>!v)} disabled={!ready}><Text style={s.eye}>👁️</Text></Pressable></View><Text style={s.label}>{L('Confirm password','Confirmer le mot de passe','Confirmar contraseña')}</Text><TextInput secureTextEntry={!show} value={confirm} onChangeText={setConfirm} style={s.input} editable={ready}/><Pressable disabled={loading||!ready} onPress={save} style={[s.primary,(loading||!ready)&&s.disabled]}><Text style={s.primaryText}>{loading?L('Saving…','Enregistrement…','Guardando…'):ready?L('Update password','Mettre à jour','Actualizar contraseña'):L('Waiting for reset link','En attente du lien','Esperando el enlace')}</Text></Pressable></View></View></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.paper},container:{flex:1,padding:24,justifyContent:'center'},eyebrow:{fontSize:11,fontWeight:'900',letterSpacing:1.5,color:colors.green},title:{fontSize:34,lineHeight:39,fontWeight:'900',color:colors.ink,marginTop:8},sub:{fontSize:14,lineHeight:21,color:colors.muted,marginTop:9},card:{backgroundColor:colors.white,borderWidth:1,borderColor:colors.line,borderRadius:radii.lg,padding:18,marginTop:24},label:{fontSize:12,fontWeight:'800',color:colors.ink,marginTop:12,marginBottom:7},password:{height:52,borderWidth:1,borderColor:colors.line,borderRadius:radii.md,backgroundColor:colors.paper,flexDirection:'row',alignItems:'center',paddingRight:12},passInput:{flex:1,height:50,paddingHorizontal:14,fontSize:16,color:colors.ink},eye:{fontSize:20},input:{height:52,borderWidth:1,borderColor:colors.line,borderRadius:radii.md,backgroundColor:colors.paper,paddingHorizontal:14,fontSize:16,color:colors.ink},primary:{height:55,borderRadius:radii.md,backgroundColor:colors.ink,alignItems:'center',justifyContent:'center',marginTop:18},disabled:{opacity:.55},primaryText:{color:colors.white,fontWeight:'900',fontSize:15}});