import { useEffect, useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { colors, radii } from '../lib/theme';
import { supabase } from '../lib/supabase';

export default function ResetPassword(){
 const[password,setPassword]=useState('');const[confirm,setConfirm]=useState('');const[show,setShow]=useState(false);const[loading,setLoading]=useState(false);const[ready,setReady]=useState(false);
 useEffect(()=>{let mounted=true;supabase?.auth.getSession().then(({data})=>{if(mounted)setReady(Boolean(data.session));});const sub=supabase?.auth.onAuthStateChange((event,session)=>{if(mounted&&(event==='PASSWORD_RECOVERY'||session))setReady(true)});return()=>{mounted=false;sub?.data.subscription.unsubscribe()};},[]);
 async function save(){if(!supabase)return;if(!ready)return Alert.alert('Reset link required','Open the password reset link from your email before choosing a new password.');if(password.length<8||!/[A-Z]/.test(password)||!/[a-z]/.test(password)||!/\d/.test(password))return Alert.alert('Password too weak','Use at least 8 characters with uppercase, lowercase and a number.');if(password!==confirm)return Alert.alert('Passwords do not match','Enter the same password twice.');setLoading(true);const{error}=await supabase.auth.updateUser({password});setLoading(false);if(error)return Alert.alert('Could not update password',error.message);await supabase.auth.signOut();Alert.alert('Password updated','Your password has been changed.');router.replace('/auth')}
 return <SafeAreaView style={s.safe}><View style={s.container}><Text style={s.eyebrow}>NEW PASSWORD</Text><Text style={s.title}>Choose a new password.</Text><Text style={s.sub}>{ready?'Use a strong password you do not reuse elsewhere.':'Open the secure reset link from your email to continue.'}</Text><View style={s.card}><Text style={s.label}>New password</Text><View style={s.password}><TextInput secureTextEntry={!show} value={password} onChangeText={setPassword} style={s.passInput} editable={ready}/><Pressable onPress={()=>setShow(v=>!v)} disabled={!ready}><Text style={s.eye}>👁️</Text></Pressable></View><Text style={s.label}>Confirm password</Text><TextInput secureTextEntry={!show} value={confirm} onChangeText={setConfirm} style={s.input} editable={ready}/><Pressable disabled={loading||!ready} onPress={save} style={[s.primary,(loading||!ready)&&s.disabled]}><Text style={s.primaryText}>{loading?'Saving…':ready?'Update password':'Waiting for reset link'}</Text></Pressable></View></View></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.paper},container:{flex:1,padding:24,justifyContent:'center'},eyebrow:{fontSize:11,fontWeight:'900',letterSpacing:1.5,color:colors.green},title:{fontSize:34,lineHeight:39,fontWeight:'900',color:colors.ink,marginTop:8},sub:{fontSize:14,lineHeight:21,color:colors.muted,marginTop:9},card:{backgroundColor:colors.white,borderWidth:1,borderColor:colors.line,borderRadius:radii.lg,padding:18,marginTop:24},label:{fontSize:12,fontWeight:'800',color:colors.ink,marginTop:12,marginBottom:7},password:{height:52,borderWidth:1,borderColor:colors.line,borderRadius:radii.md,backgroundColor:colors.paper,flexDirection:'row',alignItems:'center',paddingRight:12},passInput:{flex:1,height:50,paddingHorizontal:14,fontSize:16,color:colors.ink},eye:{fontSize:20},input:{height:52,borderWidth:1,borderColor:colors.line,borderRadius:radii.md,backgroundColor:colors.paper,paddingHorizontal:14,fontSize:16,color:colors.ink},primary:{height:55,borderRadius:radii.md,backgroundColor:colors.ink,alignItems:'center',justifyContent:'center',marginTop:18},disabled:{opacity:.55},primaryText:{color:colors.white,fontWeight:'900',fontSize:15}});