import { getLocales } from 'expo-localization';
export type Language='en'|'fr'|'es';
export type Currency='EUR'|'USD'|'GBP'|'CHF';
export const supportedLanguages=[{code:'en' as Language,label:'English'},{code:'fr' as Language,label:'Français'},{code:'es' as Language,label:'Español'}] as const;
export const supportedCurrencies=[{code:'EUR' as Currency,label:'Euro',symbol:'€'},{code:'USD' as Currency,label:'US Dollar',symbol:'$'},{code:'GBP' as Currency,label:'British Pound',symbol:'£'},{code:'CHF' as Currency,label:'Swiss Franc',symbol:'CHF'}] as const;
export const supportedCountries=[['FR','France','EUR'],['ES','Spain','EUR'],['DE','Germany','EUR'],['IT','Italy','EUR'],['PT','Portugal','EUR'],['BE','Belgium','EUR'],['NL','Netherlands','EUR'],['IE','Ireland','EUR'],['AT','Austria','EUR'],['GR','Greece','EUR'],['CY','Cyprus','EUR'],['LU','Luxembourg','EUR'],['FI','Finland','EUR'],['SE','Sweden','SEK'],['DK','Denmark','DKK'],['NO','Norway','NOK'],['CH','Switzerland','CHF'],['GB','United Kingdom','GBP'],['US','United States','USD'],['CA','Canada','CAD'],['AU','Australia','AUD'],['JP','Japan','JPY']] as const;
export function deviceLanguage():Language{const code=getLocales()[0]?.languageCode||'en';return code==='fr'||code==='es'?code:'en'}
export function formatMoney(cents:number,currency='EUR',locale?:string){try{return new Intl.NumberFormat(locale||undefined,{style:'currency',currency,maximumFractionDigits:0}).format(cents/100)}catch{return `${(cents/100).toFixed(0)} ${currency}`}}

const messages={
 en:{settings:'Settings',language:'Language',currency:'Display currency',preferences:'Preferences',save:'Save preferences',saved:'Preferences saved',english:'English',french:'French',spanish:'Spanish',currencyNote:'Currency preference controls display only. Mission offers and contracts keep their original currency.',hello:'Hello',availableDays:'available days',searchWork:'search work',network:'network',nearBase:'Near your base',searchFilters:'Search & filters',messages:'Messages',profile:'Profile',home:'Home',work:'Work',organization:'Organization',createAssignment:'Create an assignment',findProfessionals:'Find professionals',assignments:'Assignments',recentAssignments:'Recent assignments'},
 fr:{settings:'Réglages',language:'Langue',currency:"Devise d’affichage",preferences:'Préférences',save:'Enregistrer',saved:'Préférences enregistrées',english:'Anglais',french:'Français',spanish:'Espagnol',currencyNote:"La devise choisie concerne l’affichage. Les offres et contrats gardent toujours leur devise d’origine.",hello:'Bonjour',availableDays:'jours disponibles',searchWork:'chercher du travail',network:'réseau',nearBase:'Près de votre base',searchFilters:'Recherche et filtres',messages:'Messages',profile:'Profil',home:'Accueil',work:'Missions',organization:'Organisation',createAssignment:'Créer une mission',findProfessionals:'Trouver des professionnels',assignments:'Missions',recentAssignments:'Missions récentes'},
 es:{settings:'Ajustes',language:'Idioma',currency:'Moneda de visualización',preferences:'Preferencias',save:'Guardar preferencias',saved:'Preferencias guardadas',english:'Inglés',french:'Francés',spanish:'Español',currencyNote:'La moneda elegida solo afecta a la visualización. Las ofertas y contratos mantienen siempre su moneda original.',hello:'Hola',availableDays:'días disponibles',searchWork:'buscar trabajo',network:'red',nearBase:'Cerca de tu base',searchFilters:'Búsqueda y filtros',messages:'Mensajes',profile:'Perfil',home:'Inicio',work:'Misiones',organization:'Organización',createAssignment:'Crear una misión',findProfessionals:'Buscar profesionales',assignments:'Misiones',recentAssignments:'Misiones recientes'}
} as const;
export type TranslationKey=keyof typeof messages.en;
export function t(language:Language,key:TranslationKey){return messages[language]?.[key]||messages.en[key]}
